<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run ()
    {
        DB::table( 'cities' )->insert( [
            [ "id" => 1, "state_id" => 1, "name" => "ANCHORAGE", "slug" => "anchorage", "short_code" => "AK", "status" => 1 ],
            [ "id" => 2, "state_id" => 2, "name" => "ATHENS", "slug" => "athens", "short_code" => "AL", "status" => 1 ],
            [ "id" => 3, "state_id" => 2, "name" => "ATTALA", "slug" => "attala", "short_code" => "AL", "status" => 1 ],
            [ "id" => 4, "state_id" => 2, "name" => "BESSEMER", "slug" => "bessemer", "short_code" => "", "status" => 1 ],
            [ "id" => 5, "state_id" => 2, "name" => "BIRMINGHAM", "slug" => "birmingham", "short_code" => "", "status" => 1 ],
            [ "id" => 6, "state_id" => 2, "name" => "DOTHAN", "slug" => "dothan", "short_code" => "", "status" => 1 ],
            [ "id" => 7, "state_id" => 2, "name" => "EIGHT MILE", "slug" => "eight-mile", "short_code" => "", "status" => 1 ],
            [ "id" => 8, "state_id" => 2, "name" => "HNTS VILLE", "slug" => "hnts-ville", "short_code" => "", "status" => 1 ],
            [ "id" => 9, "state_id" => 2, "name" => "HEAD LAND", "slug" => "head-land", "short_code" => "", "status" => 1 ],
            [ "id" => 10, "state_id" => 2, "name" => "HUEYTOWN", "slug" => "hueytown", "short_code" => "", "status" => 1 ],
            [ "id" => 11, "state_id" => 2, "name" => "MOODY", "slug" => "moody", "short_code" => "", "status" => 1 ],
            [ "id" => 12, "state_id" => 2, "name" => "MOBILE", "slug" => "mobile", "short_code" => "", "status" => 1 ],
            [ "id" => 13, "state_id" => 2, "name" => "MONTGOMERY", "slug" => "montgomery", "short_code" => "", "status" => 1 ],
            [ "id" => 14, "state_id" => 2, "name" => "TANNER", "slug" => "tanner", "short_code" => "", "status" => 1 ],
            [ "id" => 15, "state_id" => 3, "name" => "LINCOLN", "slug" => "lincoln", "short_code" => "", "status" => 1 ],
            [ "id" => 16, "state_id" => 3, "name" => "CONWAY", "slug" => "conway", "short_code" => "", "status" => 1 ],
            [ "id" => 17, "state_id" => 3, "name" => "LITTLE ROCK", "slug" => "little-rock", "short_code" => "", "status" => 1 ],
            [ "id" => 18, "state_id" => 3, "name" => "FAYETTEVILLE", "slug" => "fayetteville", "short_code" => "", "status" => 1 ],
            [ "id" => 19, "state_id" => 1, "name" => "Test", "slug" => "test", "short_code" => "", "status" => 1 ],
            [ "id" => 20, "state_id" => 3, "name" => "NORTH LITTILE ROCK", "slug" => "north-littile-rock", "short_code" => "", "status" => 1 ],
            [ "id" => 21, "state_id" => 3, "name" => "PRAIRE GROVE", "slug" => "praire-grove", "short_code" => "", "status" => 1 ],
            [ "id" => 22, "state_id" => 3, "name" => "SCOTT", "slug" => "scott", "short_code" => "", "status" => 1 ],
            [ "id" => 23, "state_id" => 4, "name" => "PHOENIX", "slug" => "phoenix", "short_code" => "", "status" => 1 ],
            [ "id" => 24, "state_id" => 4, "name" => "TOLLESON", "slug" => "tolleson", "short_code" => "", "status" => 1 ],
            [ "id" => 25, "state_id" => 4, "name" => "TUCSON", "slug" => "tucson", "short_code" => "", "status" => 1 ],
            [ "id" => 26, "state_id" => 4, "name" => "CHANDLER", "slug" => "chandler", "short_code" => "", "status" => 1 ],
            [ "id" => 27, "state_id" => 5, "name" => "ANAHEIM", "slug" => "anaheim", "short_code" => "", "status" => 1 ],
            [ "id" => 28, "state_id" => 5, "name" => "ANTELOPE", "slug" => "antelope", "short_code" => "", "status" => 1 ],
            [ "id" => 29, "state_id" => 5, "name" => "BURBANK", "slug" => "burbank", "short_code" => "", "status" => 1 ],
            [ "id" => 30, "state_id" => 5, "name" => "BAKERSFIELD", "slug" => "bakersfield", "short_code" => "", "status" => 1 ],
            [ "id" => 31, "state_id" => 5, "name" => "BAY POINT", "slug" => "bay-point", "short_code" => "", "status" => 1 ],
            [ "id" => 32, "state_id" => 5, "name" => "BUENA PARK", "slug" => "buena-park", "short_code" => "", "status" => 1 ],
            [ "id" => 33, "state_id" => 5, "name" => "COLTON", "slug" => "colton", "short_code" => "", "status" => 1 ],
            [ "id" => 34, "state_id" => 5, "name" => "COSTA MESA", "slug" => "costa-mesa", "short_code" => "", "status" => 1 ],
            [ "id" => 35, "state_id" => 5, "name" => "EAST BAY", "slug" => "east-bay", "short_code" => "", "status" => 1 ],
            [ "id" => 36, "state_id" => 5, "name" => "FRESNO", "slug" => "fresno", "short_code" => "", "status" => 1 ],
            [ "id" => 37, "state_id" => 5, "name" => "FONTANA", "slug" => "fontana", "short_code" => "", "status" => 1 ],
            [ "id" => 38, "state_id" => 5, "name" => "FREMONT", "slug" => "fremont", "short_code" => "", "status" => 1 ],
            [ "id" => 39, "state_id" => 5, "name" => "GARDENA", "slug" => "gardena", "short_code" => "", "status" => 1 ],
            [ "id" => 40, "state_id" => 5, "name" => "HASPERIA", "slug" => "hasperia", "short_code" => "", "status" => 1 ],
            [ "id" => 41, "state_id" => 5, "name" => "HAYWAYRD", "slug" => "haywayrd", "short_code" => "", "status" => 1 ],
            [ "id" => 42, "state_id" => 5, "name" => "HIGH DESERT", "slug" => "high-desert", "short_code" => "", "status" => 1 ],
            [ "id" => 43, "state_id" => 5, "name" => "LA MESA", "slug" => "la-mesa", "short_code" => "", "status" => 1 ],
            [ "id" => 44, "state_id" => 5, "name" => "LOS ANGELES", "slug" => "los-angeles", "short_code" => "", "status" => 1 ],
            [ "id" => 45, "state_id" => 5, "name" => "LANCASTER", "slug" => "lancaster", "short_code" => "", "status" => 1 ],
            [ "id" => 46, "state_id" => 5, "name" => "LONG BEACH", "slug" => "long-beach", "short_code" => "", "status" => 1 ],
            [ "id" => 47, "state_id" => 5, "name" => "MARTINEZ", "slug" => "martinez", "short_code" => "", "status" => 1 ],
            [ "id" => 48, "state_id" => 5, "name" => "MIRA LOMA", "slug" => "mira-loma", "short_code" => "", "status" => 1 ],
            [ "id" => 49, "state_id" => 5, "name" => "NORTH HOLLYWOOD", "slug" => "north-hollywood", "short_code" => "", "status" => 1 ],
            [ "id" => 50, "state_id" => 5, "name" => "PITTSBURGH", "slug" => "pittsburgh", "short_code" => "", "status" => 1 ],
            [ "id" => 51, "state_id" => 5, "name" => "RANCHO CUCAMONGA", "slug" => "rancho-cucamonga", "short_code" => "", "status" => 1 ],
            [ "id" => 52, "state_id" => 5, "name" => "RANCHO CORDOVA", "slug" => "rancho-cordova", "short_code" => "", "status" => 1 ],
            [ "id" => 53, "state_id" => 5, "name" => "RIO LINDA", "slug" => "rio-linda", "short_code" => "", "status" => 1 ],
            [ "id" => 54, "state_id" => 5, "name" => "RIVERSIDE", "slug" => "riverside", "short_code" => "", "status" => 1 ],
            [ "id" => 55, "state_id" => 5, "name" => "SACRAMENTO", "slug" => "sacramento", "short_code" => "", "status" => 1 ],
            [ "id" => 56, "state_id" => 5, "name" => "SAN BERNARDINO", "slug" => "san-bernardino", "short_code" => "", "status" => 1 ],
            [ "id" => 57, "state_id" => 5, "name" => "SAN DIEGO", "slug" => "san-diego", "short_code" => "", "status" => 1 ],
            [ "id" => 58, "state_id" => 5, "name" => "SAN JOSE", "slug" => "san-jose", "short_code" => "", "status" => 1 ],
            [ "id" => 59, "state_id" => 5, "name" => "SAN MARTIN", "slug" => "san-martin", "short_code" => "", "status" => 1 ],
            [ "id" => 60, "state_id" => 5, "name" => "SANTA PAULA", "slug" => "santa-paula", "short_code" => "", "status" => 1 ],
            [ "id" => 61, "state_id" => 5, "name" => "SOUTH SACRAMENTO", "slug" => "south-sacramento", "short_code" => "", "status" => 1 ],
            [ "id" => 62, "state_id" => 5, "name" => "SUN VALLEY", "slug" => "sun-valley", "short_code" => "", "status" => 1 ],
            [ "id" => 63, "state_id" => 5, "name" => "TRACY", "slug" => "tracy", "short_code" => "", "status" => 1 ],
            [ "id" => 64, "state_id" => 5, "name" => "VALLEJO", "slug" => "vallejo", "short_code" => "", "status" => 1 ],
            [ "id" => 65, "state_id" => 5, "name" => "VAN NUYS", "slug" => "van-nuys", "short_code" => "", "status" => 1 ],
            [ "id" => 66, "state_id" => 5, "name" => "WILMINGTON", "slug" => "wilmington", "short_code" => "", "status" => 1 ],
            [ "id" => 67, "state_id" => 6, "name" => "AURORA", "slug" => "aurora", "short_code" => "", "status" => 1 ],
            [ "id" => 68, "state_id" => 6, "name" => "BRIGHTON", "slug" => "brighton", "short_code" => "", "status" => 1 ],
            [ "id" => 69, "state_id" => 6, "name" => "COLORADO SPRINGS", "slug" => "colorado-springs", "short_code" => "", "status" => 1 ],
            [ "id" => 70, "state_id" => 6, "name" => "COMMERCE CITY", "slug" => "commerce-city", "short_code" => "", "status" => 1 ],
            [ "id" => 71, "state_id" => 6, "name" => "DELTA", "slug" => "delta", "short_code" => "", "status" => 1 ],
            [ "id" => 72, "state_id" => 6, "name" => "DENVER", "slug" => "denver", "short_code" => "", "status" => 1 ],
            [ "id" => 73, "state_id" => 6, "name" => "DENVER CENTRAL", "slug" => "denver-central", "short_code" => "", "status" => 1 ],
            [ "id" => 74, "state_id" => 6, "name" => "DENVER EAST", "slug" => "denver-east", "short_code" => "", "status" => 1 ],
            [ "id" => 75, "state_id" => 6, "name" => "FOUNTAIN", "slug" => "fountain", "short_code" => "", "status" => 1 ],
            [ "id" => 76, "state_id" => 6, "name" => "LITTLETON", "slug" => "littleton", "short_code" => "", "status" => 1 ],
            [ "id" => 77, "state_id" => 6, "name" => "MACK", "slug" => "mack", "short_code" => "", "status" => 1 ],
            [ "id" => 78, "state_id" => 6, "name" => "PUEBLO", "slug" => "pueblo", "short_code" => "", "status" => 1 ],
            [ "id" => 79, "state_id" => 6, "name" => "WESTERN COLARADO", "slug" => "western-colarado", "short_code" => "", "status" => 1 ],
            [ "id" => 80, "state_id" => 7, "name" => "BERLIN", "slug" => "berlin", "short_code" => "", "status" => 1 ],
            [ "id" => 81, "state_id" => 7, "name" => "EAST WINDSOR", "slug" => "east-windsor", "short_code" => "", "status" => 1 ],
            [ "id" => 82, "state_id" => 7, "name" => "HARTFORD SOUTH", "slug" => "hartford-south", "short_code" => "", "status" => 1 ],
            [ "id" => 83, "state_id" => 7, "name" => "HAMOND", "slug" => "hamond", "short_code" => "", "status" => 1 ],
            [ "id" => 84, "state_id" => 7, "name" => "HAMDEN CT (M)", "slug" => "hamden-ct-m", "short_code" => "", "status" => 1 ],
            [ "id" => 85, "state_id" => 7, "name" => "HARTFORD ", "slug" => "hartford", "short_code" => "", "status" => 1 ],
            [ "id" => 86, "state_id" => 7, "name" => "MIDDLE TOWN", "slug" => "middle-town", "short_code" => "", "status" => 1 ],
            [ "id" => 87, "state_id" => 7, "name" => "NEW BRITAIN", "slug" => "new-britain", "short_code" => "", "status" => 1 ],
            [ "id" => 88, "state_id" => 8, "name" => "SEAFORD", "slug" => "seaford", "short_code" => "", "status" => 1 ],
            [ "id" => 89, "state_id" => 8, "name" => "NEW CASTLE", "slug" => "new-castle", "short_code" => "", "status" => 1 ],
            [ "id" => 90, "state_id" => 9, "name" => "APOPKA", "slug" => "apopka", "short_code" => "", "status" => 1 ],
            [ "id" => 91, "state_id" => 9, "name" => "BRADENTON", "slug" => "bradenton", "short_code" => "", "status" => 1 ],
            [ "id" => 92, "state_id" => 9, "name" => "CLEARWATER", "slug" => "clearwater", "short_code" => "", "status" => 1 ],
            [ "id" => 93, "state_id" => 9, "name" => "DAVIE", "slug" => "davie", "short_code" => "", "status" => 1 ],
            [ "id" => 94, "state_id" => 9, "name" => "DEFUNIAK SPRINGS", "slug" => "defuniak-springs", "short_code" => "", "status" => 1 ],
            [ "id" => 95, "state_id" => 9, "name" => "FORT LAUDERDALE", "slug" => "fort-lauderdale", "short_code" => "", "status" => 1 ],
            [ "id" => 96, "state_id" => 9, "name" => "FORT MYERS", "slug" => "fort-myers", "short_code" => "", "status" => 1 ],
            [ "id" => 97, "state_id" => 9, "name" => "FORT PIERCE", "slug" => "fort-pierce", "short_code" => "", "status" => 1 ],
            [ "id" => 98, "state_id" => 9, "name" => "HOMESTEAD", "slug" => "homestead", "short_code" => "", "status" => 1 ],
            [ "id" => 99, "state_id" => 9, "name" => "HUDSON", "slug" => "hudson", "short_code" => "", "status" => 1 ],
            [ "id" => 100, "state_id" => 9, "name" => "JAX", "slug" => "jax", "short_code" => "", "status" => 1 ],
            [ "id" => 101, "state_id" => 9, "name" => "JACKSONVILLE", "slug" => "jacksonville", "short_code" => "", "status" => 1 ],
            [ "id" => 102, "state_id" => 9, "name" => "JACKSONVILLE EAST", "slug" => "jacksonville-east", "short_code" => "", "status" => 1 ],
            [ "id" => 103, "state_id" => 9, "name" => "JACKSONVILLE WEST", "slug" => "jacksonville-west", "short_code" => "", "status" => 1 ],
            [ "id" => 104, "state_id" => 9, "name" => "MIAMI CENTRAL", "slug" => "miami-central", "short_code" => "", "status" => 1 ],
            [ "id" => 105, "state_id" => 9, "name" => "MIAMI NORTH", "slug" => "miami-north", "short_code" => "", "status" => 1 ],
            [ "id" => 106, "state_id" => 9, "name" => "MIAMI SOUTH", "slug" => "miami-south", "short_code" => "", "status" => 1 ],
            [ "id" => 107, "state_id" => 9, "name" => "MIDWAY", "slug" => "midway", "short_code" => "", "status" => 1 ],
            [ "id" => 108, "state_id" => 9, "name" => "MILTON", "slug" => "milton", "short_code" => "", "status" => 1 ],
            [ "id" => 109, "state_id" => 9, "name" => "NORTH FORT MYRES", "slug" => "north-fort-myres", "short_code" => "", "status" => 1 ],
            [ "id" => 110, "state_id" => 9, "name" => "OCOEE", "slug" => "ocoee", "short_code" => "", "status" => 1 ],
            [ "id" => 111, "state_id" => 9, "name" => "OCALA", "slug" => "ocala", "short_code" => "", "status" => 1 ],
            [ "id" => 112, "state_id" => 9, "name" => "OPA LOCKA", "slug" => "opa-locka", "short_code" => "", "status" => 1 ],
            [ "id" => 113, "state_id" => 9, "name" => "ORLANDO", "slug" => "orlando", "short_code" => "", "status" => 1 ],
            [ "id" => 114, "state_id" => 9, "name" => "ORLANDO NORTH", "slug" => "orlando-north", "short_code" => "", "status" => 1 ],
            [ "id" => 115, "state_id" => 9, "name" => "PALMETTO", "slug" => "palmetto", "short_code" => "", "status" => 1 ],
            [ "id" => 116, "state_id" => 9, "name" => "PENSACACOLA", "slug" => "pensacacola", "short_code" => "", "status" => 1 ],
            [ "id" => 117, "state_id" => 9, "name" => "PUNTA GORDA", "slug" => "punta-gorda", "short_code" => "", "status" => 1 ],
            [ "id" => 118, "state_id" => 9, "name" => "RIVERVIEW", "slug" => "riverview", "short_code" => "", "status" => 1 ],
            [ "id" => 119, "state_id" => 9, "name" => "SANFORD", "slug" => "sanford", "short_code" => "", "status" => 1 ],
            [ "id" => 120, "state_id" => 9, "name" => "TALLAHASSEE", "slug" => "tallahassee", "short_code" => "", "status" => 1 ],
            [ "id" => 121, "state_id" => 9, "name" => "TAMPA  ", "slug" => "tampa", "short_code" => "", "status" => 1 ],
            [ "id" => 122, "state_id" => 9, "name" => "TAMPA SOUTH", "slug" => "tampa-south", "short_code" => "", "status" => 1 ],
            [ "id" => 123, "state_id" => 9, "name" => "WEST PALM BEACH", "slug" => "west-palm-beach", "short_code" => "", "status" => 1 ],
            [ "id" => 124, "state_id" => 10, "name" => "ACWORTH", "slug" => "acworth", "short_code" => "", "status" => 1 ],
            [ "id" => 125, "state_id" => 10, "name" => "AUSTELL", "slug" => "austell", "short_code" => "", "status" => 1 ],
            [ "id" => 126, "state_id" => 10, "name" => "ATLANTA", "slug" => "atlanta", "short_code" => "", "status" => 1 ],
            [ "id" => 127, "state_id" => 10, "name" => "ATLANTA EAST", "slug" => "atlanta-east", "short_code" => "", "status" => 1 ],
            [ "id" => 128, "state_id" => 10, "name" => "ATLANTA EAST", "slug" => "atlanta-east-2", "short_code" => "", "status" => 1 ],
            [ "id" => 129, "state_id" => 10, "name" => "ATLANTA NORTH", "slug" => "atlanta-north", "short_code" => "", "status" => 1 ],
            [ "id" => 130, "state_id" => 15, "name" => "HAMMOND", "slug" => "hammond", "short_code" => "", "status" => 1 ],
            [ "id" => 131, "state_id" => 10, "name" => "ATLANTA SOUTH", "slug" => "atlanta-south", "short_code" => "", "status" => 1 ],
            [ "id" => 132, "state_id" => 10, "name" => "ATLANTA WEST", "slug" => "atlanta-west", "short_code" => "", "status" => 1 ],
            [ "id" => 133, "state_id" => 10, "name" => "BYRON", "slug" => "byron", "short_code" => "", "status" => 1 ],
            [ "id" => 134, "state_id" => 10, "name" => "CARTERSVILLE", "slug" => "cartersville", "short_code" => "", "status" => 1 ],
            [ "id" => 135, "state_id" => 10, "name" => "COLLEGE PARK", "slug" => "college-park", "short_code" => "", "status" => 1 ],
            [ "id" => 136, "state_id" => 10, "name" => "DOUGLASVILLE", "slug" => "douglasville", "short_code" => "", "status" => 1 ],
            [ "id" => 137, "state_id" => 10, "name" => "ELLENWOOD", "slug" => "ellenwood", "short_code" => "", "status" => 1 ],
            [ "id" => 138, "state_id" => 10, "name" => "FAIRBURN", "slug" => "fairburn", "short_code" => "", "status" => 1 ],
            [ "id" => 139, "state_id" => 10, "name" => "GAINESVILLE", "slug" => "gainesville", "short_code" => "", "status" => 1 ],
            [ "id" => 140, "state_id" => 10, "name" => "LAKE CITY", "slug" => "lake-city", "short_code" => "", "status" => 1 ],
            [ "id" => 141, "state_id" => 10, "name" => "LOGANVILLE", "slug" => "loganville", "short_code" => "", "status" => 1 ],
            [ "id" => 142, "state_id" => 10, "name" => "MACON", "slug" => "macon", "short_code" => "", "status" => 1 ],
            [ "id" => 143, "state_id" => 10, "name" => "METTER", "slug" => "metter", "short_code" => "", "status" => 1 ],
            [ "id" => 144, "state_id" => 10, "name" => "MORROW", "slug" => "morrow", "short_code" => "", "status" => 1 ],
            [ "id" => 145, "state_id" => 10, "name" => "RINCOW", "slug" => "rincow", "short_code" => "", "status" => 1 ],
            [ "id" => 146, "state_id" => 10, "name" => "SAVAHHAH", "slug" => "savahhah", "short_code" => "", "status" => 1 ],
            [ "id" => 147, "state_id" => 10, "name" => "TIFTON", "slug" => "tifton", "short_code" => "", "status" => 1 ],
            [ "id" => 148, "state_id" => 10, "name" => "WINDER", "slug" => "winder", "short_code" => "", "status" => 1 ],
            [ "id" => 149, "state_id" => 11, "name" => "HONOLULU", "slug" => "honolulu", "short_code" => "", "status" => 1 ],
            [ "id" => 150, "state_id" => 11, "name" => "KAHULUI", "slug" => "kahului", "short_code" => "", "status" => 1 ],
            [ "id" => 151, "state_id" => 11, "name" => "HILO", "slug" => "hilo", "short_code" => "", "status" => 1 ],
            [ "id" => 152, "state_id" => 11, "name" => "KONA", "slug" => "kona", "short_code" => "", "status" => 1 ],
            [ "id" => 153, "state_id" => 11, "name" => "LIHUE", "slug" => "lihue", "short_code" => "", "status" => 1 ],
            [ "id" => 154, "state_id" => 11, "name" => "GUAM", "slug" => "guam", "short_code" => "", "status" => 1 ],
            [ "id" => 155, "state_id" => 12, "name" => "DES MOINES", "slug" => "des-moines", "short_code" => "", "status" => 1 ],
            [ "id" => 156, "state_id" => 12, "name" => "DEVEN PORT", "slug" => "deven-port", "short_code" => "", "status" => 1 ],
            [ "id" => 157, "state_id" => 12, "name" => "DE SOTO", "slug" => "de-soto", "short_code" => "", "status" => 1 ],
            [ "id" => 158, "state_id" => 12, "name" => "ELDRIDGE", "slug" => "eldridge", "short_code" => "", "status" => 1 ],
            [ "id" => 159, "state_id" => 12, "name" => "GRIMES", "slug" => "grimes", "short_code" => "", "status" => 1 ],
            [ "id" => 160, "state_id" => 13, "name" => "BOISE", "slug" => "boise", "short_code" => "", "status" => 1 ],
            [ "id" => 161, "state_id" => 13, "name" => "MERDIAN", "slug" => "merdian", "short_code" => "", "status" => 1 ],
            [ "id" => 162, "state_id" => 13, "name" => "NAMPA", "slug" => "nampa", "short_code" => "", "status" => 1 ],
            [ "id" => 163, "state_id" => 14, "name" => "AURORA", "slug" => "aurora-2", "short_code" => "", "status" => 1 ],
            [ "id" => 164, "state_id" => 14, "name" => "BARLETT", "slug" => "barlett", "short_code" => "", "status" => 1 ],
            [ "id" => 165, "state_id" => 14, "name" => "BLUE ISLAND", "slug" => "blue-island", "short_code" => "", "status" => 1 ],
            [ "id" => 166, "state_id" => 14, "name" => "BOLING BROOK", "slug" => "boling-brook", "short_code" => "", "status" => 1 ],
            [ "id" => 167, "state_id" => 14, "name" => "CHICAGO", "slug" => "chicago", "short_code" => "", "status" => 1 ],
            [ "id" => 168, "state_id" => 14, "name" => "CHICAGO NORTH", "slug" => "chicago-north", "short_code" => "", "status" => 1 ],
            [ "id" => 169, "state_id" => 14, "name" => "CHICAGO SOUTH", "slug" => "chicago-south", "short_code" => "", "status" => 1 ],
            [ "id" => 170, "state_id" => 14, "name" => "CHICAGO WEST", "slug" => "chicago-west", "short_code" => "", "status" => 1 ],
            [ "id" => 171, "state_id" => 14, "name" => "CHICAGO HEIGHTS", "slug" => "chicago-heights", "short_code" => "", "status" => 1 ],
            [ "id" => 172, "state_id" => 14, "name" => "CT SPRING FIELD", "slug" => "ct-spring-field", "short_code" => "", "status" => 1 ],
            [ "id" => 173, "state_id" => 14, "name" => "CENTREVILLE", "slug" => "centreville", "short_code" => "", "status" => 1 ],
            [ "id" => 174, "state_id" => 14, "name" => "DUNDEE", "slug" => "dundee", "short_code" => "", "status" => 1 ],
            [ "id" => 175, "state_id" => 14, "name" => "DES MOINES", "slug" => "des-moines-2", "short_code" => "", "status" => 1 ],
            [ "id" => 176, "state_id" => 14, "name" => "ELGIN", "slug" => "elgin", "short_code" => "", "status" => 1 ],
            [ "id" => 177, "state_id" => 14, "name" => "EAST ST LOUIS IL", "slug" => "east-st-louis-il", "short_code" => "", "status" => 1 ],
            [ "id" => 178, "state_id" => 14, "name" => "EIGHT MILE ", "slug" => "eight-mile-2", "short_code" => "", "status" => 1 ],
            [ "id" => 179, "state_id" => 14, "name" => "GRANITE CITY", "slug" => "granite-city", "short_code" => "", "status" => 1 ],
            [ "id" => 180, "state_id" => 14, "name" => "LINCOLN", "slug" => "lincoln-2", "short_code" => "", "status" => 1 ],
            [ "id" => 181, "state_id" => 14, "name" => "MARKHAM", "slug" => "markham", "short_code" => "", "status" => 1 ],
            [ "id" => 182, "state_id" => 14, "name" => "MATTESSON", "slug" => "mattesson", "short_code" => "", "status" => 1 ],
            [ "id" => 183, "state_id" => 14, "name" => "MONTGOMERY", "slug" => "montgomery-2", "short_code" => "", "status" => 1 ],
            [ "id" => 184, "state_id" => 14, "name" => "PEORIA", "slug" => "peoria", "short_code" => "", "status" => 1 ],
            [ "id" => 185, "state_id" => 14, "name" => "PEKIN", "slug" => "pekin", "short_code" => "", "status" => 1 ],
            [ "id" => 186, "state_id" => 14, "name" => "ST. LOIUS", "slug" => "st-loius", "short_code" => "", "status" => 1 ],
            [ "id" => 187, "state_id" => 14, "name" => "SPRINGFIELD", "slug" => "springfield", "short_code" => "", "status" => 1 ],
            [ "id" => 188, "state_id" => 14, "name" => "WHEELING", "slug" => "wheeling", "short_code" => "", "status" => 1 ],
            [ "id" => 189, "state_id" => 15, "name" => "COLUMBUS", "slug" => "columbus", "short_code" => "", "status" => 1 ],
            [ "id" => 190, "state_id" => 15, "name" => "CLARKSVILLE", "slug" => "clarksville", "short_code" => "", "status" => 1 ],
            [ "id" => 191, "state_id" => 15, "name" => "FORT WAYNE", "slug" => "fort-wayne", "short_code" => "", "status" => 1 ],
            [ "id" => 192, "state_id" => 15, "name" => "HARTFORD CITY", "slug" => "hartford-city", "short_code" => "", "status" => 1 ],
            [ "id" => 193, "state_id" => 15, "name" => "INDIANAPOLIS", "slug" => "indianapolis", "short_code" => "", "status" => 1 ],
            [ "id" => 194, "state_id" => 15, "name" => "JEFFERSONVILLE", "slug" => "jeffersonville", "short_code" => "", "status" => 1 ],
            [ "id" => 195, "state_id" => 15, "name" => "SOUTH BEND", "slug" => "south-bend", "short_code" => "", "status" => 1 ],
            [ "id" => 196, "state_id" => 16, "name" => "KANSAS CITY", "slug" => "kansas-city", "short_code" => "", "status" => 1 ],
            [ "id" => 197, "state_id" => 16, "name" => "WICHITA", "slug" => "wichita", "short_code" => "", "status" => 1 ],
            [ "id" => 198, "state_id" => 16, "name" => "PARK CITY", "slug" => "park-city", "short_code" => "", "status" => 1 ],
            [ "id" => 199, "state_id" => 17, "name" => "ASHLAND", "slug" => "ashland", "short_code" => "", "status" => 1 ],
            [ "id" => 200, "state_id" => 17, "name" => "BOWLING GREEN", "slug" => "bowling-green", "short_code" => "", "status" => 1 ],
            [ "id" => 201, "state_id" => 17, "name" => "BLUE LEVEL", "slug" => "blue-level", "short_code" => "", "status" => 1 ],
            [ "id" => 202, "state_id" => 17, "name" => "EMINENCE", "slug" => "eminence", "short_code" => "", "status" => 1 ],
            [ "id" => 203, "state_id" => 17, "name" => "LAWRENCE BURGH", "slug" => "lawrence-burgh", "short_code" => "", "status" => 1 ],
            [ "id" => 204, "state_id" => 17, "name" => "LEXINGTON", "slug" => "lexington", "short_code" => "", "status" => 1 ],
            [ "id" => 205, "state_id" => 17, "name" => "LEXINGTON EAST", "slug" => "lexington-east", "short_code" => "", "status" => 1 ],
            [ "id" => 206, "state_id" => 17, "name" => "LEXINGTON WEST", "slug" => "lexington-west", "short_code" => "", "status" => 1 ],
            [ "id" => 207, "state_id" => 17, "name" => "LOUISSVILLE NORTH", "slug" => "louissville-north", "short_code" => "", "status" => 1 ],
            [ "id" => 208, "state_id" => 17, "name" => "LOUISVILLE", "slug" => "louisville", "short_code" => "", "status" => 1 ],
            [ "id" => 209, "state_id" => 17, "name" => "PADUCAH", "slug" => "paducah", "short_code" => "", "status" => 1 ],
            [ "id" => 210, "state_id" => 17, "name" => "SHEPHERDSVILLE", "slug" => "shepherdsville", "short_code" => "", "status" => 1 ],
            [ "id" => 211, "state_id" => 17, "name" => "WALTON", "slug" => "walton", "short_code" => "", "status" => 1 ],
            [ "id" => 212, "state_id" => 18, "name" => "BATON ROUGE", "slug" => "baton-rouge", "short_code" => "", "status" => 1 ],
            [ "id" => 213, "state_id" => 18, "name" => "GREEN WELL SPRINGS", "slug" => "green-well-springs", "short_code" => "", "status" => 1 ],
            [ "id" => 214, "state_id" => 18, "name" => "GREENWOOD", "slug" => "greenwood", "short_code" => "", "status" => 1 ],
            [ "id" => 215, "state_id" => 18, "name" => "LAFAYATTE", "slug" => "lafayatte", "short_code" => "", "status" => 1 ],
            [ "id" => 216, "state_id" => 18, "name" => "LIVINGSTONE", "slug" => "livingstone", "short_code" => "", "status" => 1 ],
            [ "id" => 217, "state_id" => 18, "name" => "NEW ORLEANS", "slug" => "new-orleans", "short_code" => "", "status" => 1 ],
            [ "id" => 218, "state_id" => 18, "name" => "SLIDELL", "slug" => "slidell", "short_code" => "", "status" => 1 ],
            [ "id" => 219, "state_id" => 18, "name" => "SHREVEPORT", "slug" => "shreveport", "short_code" => "", "status" => 1 ],
            [ "id" => 220, "state_id" => 19, "name" => "ACTION", "slug" => "action", "short_code" => "", "status" => 1 ],
            [ "id" => 221, "state_id" => 19, "name" => "BOSTON SHIRLEY", "slug" => "boston-shirley", "short_code" => "", "status" => 1 ],
            [ "id" => 222, "state_id" => 19, "name" => "COLUMBUS", "slug" => "columbus-2", "short_code" => "", "status" => 1 ],
            [ "id" => 223, "state_id" => 19, "name" => "EAST TAUNTON", "slug" => "east-taunton", "short_code" => "", "status" => 1 ],
            [ "id" => 224, "state_id" => 19, "name" => "FRTAMINGHAM", "slug" => "frtamingham", "short_code" => "", "status" => 1 ],
            [ "id" => 225, "state_id" => 19, "name" => "HARTFORD CITY", "slug" => "hartford-city-2", "short_code" => "", "status" => 1 ],
            [ "id" => 226, "state_id" => 19, "name" => "HARTFORD CITY", "slug" => "hartford-city-3", "short_code" => "", "status" => 1 ],
            [ "id" => 227, "state_id" => 19, "name" => "MENDON", "slug" => "mendon", "short_code" => "", "status" => 1 ],
            [ "id" => 228, "state_id" => 19, "name" => "NORTH BILLLERCIA", "slug" => "north-billlercia", "short_code" => "", "status" => 1 ],
            [ "id" => 229, "state_id" => 19, "name" => "NORTH DIGHTON", "slug" => "north-dighton", "short_code" => "", "status" => 1 ],
            [ "id" => 230, "state_id" => 19, "name" => "NORTH BOSTON", "slug" => "north-boston", "short_code" => "", "status" => 1 ],
            [ "id" => 231, "state_id" => 19, "name" => "SOUTH BOSTON", "slug" => "south-boston", "short_code" => "", "status" => 1 ],
            [ "id" => 232, "state_id" => 19, "name" => "ROWLEY", "slug" => "rowley", "short_code" => "", "status" => 1 ],
            [ "id" => 233, "state_id" => 19, "name" => "SHIRLEY", "slug" => "shirley", "short_code" => "", "status" => 1 ],
            [ "id" => 234, "state_id" => 19, "name" => "TAUNTON", "slug" => "taunton", "short_code" => "", "status" => 1 ],
            [ "id" => 235, "state_id" => 19, "name" => "TEMPLETTON", "slug" => "templetton", "short_code" => "", "status" => 1 ],
            [ "id" => 236, "state_id" => 19, "name" => "WEST WARREN", "slug" => "west-warren", "short_code" => "", "status" => 1 ],
            [ "id" => 237, "state_id" => 20, "name" => "BALTIMORE", "slug" => "baltimore", "short_code" => "", "status" => 1 ],
            [ "id" => 238, "state_id" => 20, "name" => "BRANDYWINE", "slug" => "brandywine", "short_code" => "", "status" => 1 ],
            [ "id" => 239, "state_id" => 20, "name" => "CURTIS BAY", "slug" => "curtis-bay", "short_code" => "", "status" => 1 ],
            [ "id" => 240, "state_id" => 20, "name" => "CONOWINGO", "slug" => "conowingo", "short_code" => "", "status" => 1 ],
            [ "id" => 241, "state_id" => 20, "name" => "DUNDALK", "slug" => "dundalk", "short_code" => "", "status" => 1 ],
            [ "id" => 242, "state_id" => 20, "name" => "ELKRIDGE", "slug" => "elkridge", "short_code" => "", "status" => 1 ],
            [ "id" => 243, "state_id" => 20, "name" => "FREDRICK", "slug" => "fredrick", "short_code" => "", "status" => 1 ],
            [ "id" => 244, "state_id" => 20, "name" => "FINKSBURGH", "slug" => "finksburgh", "short_code" => "", "status" => 1 ],
            [ "id" => 245, "state_id" => 20, "name" => "LAUREL", "slug" => "laurel", "short_code" => "", "status" => 1 ],
            [ "id" => 246, "state_id" => 20, "name" => "METRO DC", "slug" => "metro-dc", "short_code" => "", "status" => 1 ],
            [ "id" => 247, "state_id" => 20, "name" => "PATAPSCO", "slug" => "patapsco", "short_code" => "", "status" => 1 ],
            [ "id" => 248, "state_id" => 20, "name" => "PORTLAND GORHAM", "slug" => "portland-gorham", "short_code" => "", "status" => 1 ],
            [ "id" => 249, "state_id" => 20, "name" => "ROSEDALE", "slug" => "rosedale", "short_code" => "", "status" => 1 ],
            [ "id" => 250, "state_id" => 20, "name" => "SALISBURY", "slug" => "salisbury", "short_code" => "", "status" => 1 ],
            [ "id" => 251, "state_id" => 20, "name" => "SILVERSPRING", "slug" => "silverspring", "short_code" => "", "status" => 1 ],
            [ "id" => 252, "state_id" => 20, "name" => "TANEYTOWN", "slug" => "taneytown", "short_code" => "", "status" => 1 ],
            [ "id" => 253, "state_id" => 20, "name" => "WASHINGTON DC", "slug" => "washington-dc", "short_code" => "", "status" => 1 ],
            [ "id" => 254, "state_id" => 20, "name" => "WHITE MARSH", "slug" => "white-marsh", "short_code" => "", "status" => 1 ],
            [ "id" => 255, "state_id" => 20, "name" => "WHITE PLAINS", "slug" => "white-plains", "short_code" => "", "status" => 1 ],
            [ "id" => 256, "state_id" => 20, "name" => "WALDROF", "slug" => "waldrof", "short_code" => "", "status" => 1 ],
            [ "id" => 257, "state_id" => 21, "name" => "GORHAM", "slug" => "gorham", "short_code" => "", "status" => 1 ],
            [ "id" => 258, "state_id" => 21, "name" => "GREENWOOD", "slug" => "greenwood-2", "short_code" => "", "status" => 1 ],
            [ "id" => 259, "state_id" => 21, "name" => "GRAY", "slug" => "gray", "short_code" => "", "status" => 1 ],
            [ "id" => 260, "state_id" => 21, "name" => "LAYMAN", "slug" => "layman", "short_code" => "", "status" => 1 ],
            [ "id" => 261, "state_id" => 21, "name" => "ORONO", "slug" => "orono", "short_code" => "", "status" => 1 ],
            [ "id" => 262, "state_id" => 22, "name" => "BELLEVILLE", "slug" => "belleville", "short_code" => "", "status" => 1 ],
            [ "id" => 263, "state_id" => 22, "name" => "BYRON CENTRE", "slug" => "byron-centre", "short_code" => "", "status" => 1 ],
            [ "id" => 264, "state_id" => 22, "name" => "CARLETTON", "slug" => "carletton", "short_code" => "", "status" => 1 ],
            [ "id" => 265, "state_id" => 22, "name" => "DETROIT", "slug" => "detroit", "short_code" => "", "status" => 1 ],
            [ "id" => 266, "state_id" => 22, "name" => "DIVISION", "slug" => "division", "short_code" => "", "status" => 1 ],
            [ "id" => 267, "state_id" => 22, "name" => "FLINT", "slug" => "flint", "short_code" => "", "status" => 1 ],
            [ "id" => 268, "state_id" => 22, "name" => "GRAET LAKES", "slug" => "graet-lakes", "short_code" => "", "status" => 1 ],
            [ "id" => 269, "state_id" => 22, "name" => "GRANT RAPIDS", "slug" => "grant-rapids", "short_code" => "", "status" => 1 ],
            [ "id" => 270, "state_id" => 22, "name" => "IONIA", "slug" => "ionia", "short_code" => "", "status" => 1 ],
            [ "id" => 271, "state_id" => 22, "name" => "KINCHELOE", "slug" => "kincheloe", "short_code" => "", "status" => 1 ],
            [ "id" => 272, "state_id" => 22, "name" => "LANSING", "slug" => "lansing", "short_code" => "", "status" => 1 ],
            [ "id" => 273, "state_id" => 22, "name" => "NEW BOSTON", "slug" => "new-boston", "short_code" => "", "status" => 1 ],
            [ "id" => 274, "state_id" => 22, "name" => "PORTLAND", "slug" => "portland", "short_code" => "", "status" => 1 ],
            [ "id" => 275, "state_id" => 22, "name" => "ST CLAIR SHORES MI", "slug" => "st-clair-shores-mi", "short_code" => "", "status" => 1 ],
            [ "id" => 276, "state_id" => 22, "name" => "WOOD HEAVEN", "slug" => "wood-heaven", "short_code" => "", "status" => 1 ],
            [ "id" => 277, "state_id" => 23, "name" => "AVON", "slug" => "avon", "short_code" => "", "status" => 1 ],
            [ "id" => 278, "state_id" => 23, "name" => "BLAINE", "slug" => "blaine", "short_code" => "", "status" => 1 ],
            [ "id" => 279, "state_id" => 23, "name" => "BLAINE", "slug" => "blaine-2", "short_code" => "", "status" => 1 ],
            [ "id" => 280, "state_id" => 23, "name" => "EAST BETHEL", "slug" => "east-bethel", "short_code" => "", "status" => 1 ],
            [ "id" => 281, "state_id" => 23, "name" => "FRIDLEY", "slug" => "fridley", "short_code" => "", "status" => 1 ],
            [ "id" => 282, "state_id" => 23, "name" => "FARIBAULT", "slug" => "faribault", "short_code" => "", "status" => 1 ],
            [ "id" => 283, "state_id" => 23, "name" => "HAM LAKE", "slug" => "ham-lake", "short_code" => "", "status" => 1 ],
            [ "id" => 284, "state_id" => 23, "name" => "MAPLE GROVE", "slug" => "maple-grove", "short_code" => "", "status" => 1 ],
            [ "id" => 285, "state_id" => 23, "name" => "MAPLE GROVE", "slug" => "maple-grove-2", "short_code" => "", "status" => 1 ],
            [ "id" => 286, "state_id" => 23, "name" => "MINNEAPOLIS", "slug" => "minneapolis", "short_code" => "", "status" => 1 ],
            [ "id" => 287, "state_id" => 23, "name" => "MINNEAPOLIS NORTH", "slug" => "minneapolis-north", "short_code" => "", "status" => 1 ],
            [ "id" => 288, "state_id" => 23, "name" => "MINNEAPOLIS ST PAUL", "slug" => "minneapolis-st-paul", "short_code" => "", "status" => 1 ],
            [ "id" => 289, "state_id" => 23, "name" => "RED WING", "slug" => "red-wing", "short_code" => "", "status" => 1 ],
            [ "id" => 290, "state_id" => 23, "name" => "RICE", "slug" => "rice", "short_code" => "", "status" => 1 ],
            [ "id" => 291, "state_id" => 23, "name" => "SAINT PAUL", "slug" => "saint-paul", "short_code" => "", "status" => 1 ],
            [ "id" => 292, "state_id" => 23, "name" => "SHAKOPEE", "slug" => "shakopee", "short_code" => "", "status" => 1 ],
            [ "id" => 293, "state_id" => 23, "name" => "ST CLOUD", "slug" => "st-cloud", "short_code" => "", "status" => 1 ],
            [ "id" => 294, "state_id" => 24, "name" => "BRIDGETON", "slug" => "bridgeton", "short_code" => "", "status" => 1 ],
            [ "id" => 295, "state_id" => 24, "name" => "COLUMBIA", "slug" => "columbia", "short_code" => "", "status" => 1 ],
            [ "id" => 296, "state_id" => 24, "name" => "KANASCITY", "slug" => "kanascity", "short_code" => "", "status" => 1 ],
            [ "id" => 297, "state_id" => 24, "name" => "ROGERSVILLE", "slug" => "rogersville", "short_code" => "", "status" => 1 ],
            [ "id" => 298, "state_id" => 24, "name" => "SAINT LOUIS", "slug" => "saint-louis", "short_code" => "", "status" => 1 ],
            [ "id" => 299, "state_id" => 24, "name" => "SIKESTON", "slug" => "sikeston", "short_code" => "", "status" => 1 ],
            [ "id" => 300, "state_id" => 24, "name" => "SPRINGFIELD", "slug" => "springfield-2", "short_code" => "", "status" => 1 ],
            [ "id" => 301, "state_id" => 25, "name" => "BYRAM", "slug" => "byram", "short_code" => "", "status" => 1 ],
            [ "id" => 302, "state_id" => 25, "name" => "FLORENCE", "slug" => "florence", "short_code" => "", "status" => 1 ],
            [ "id" => 303, "state_id" => 25, "name" => "GRENADA", "slug" => "grenada", "short_code" => "", "status" => 1 ],
            [ "id" => 304, "state_id" => 25, "name" => "GULF COAST", "slug" => "gulf-coast", "short_code" => "", "status" => 1 ],
            [ "id" => 305, "state_id" => 25, "name" => "HATTIESBURGH", "slug" => "hattiesburgh", "short_code" => "", "status" => 1 ],
            [ "id" => 306, "state_id" => 25, "name" => "JACKSON", "slug" => "jackson", "short_code" => "", "status" => 1 ],
            [ "id" => 307, "state_id" => 25, "name" => "MOSSPOINT", "slug" => "mosspoint", "short_code" => "", "status" => 1 ],
            [ "id" => 308, "state_id" => 26, "name" => "BILLINGS", "slug" => "billings", "short_code" => "", "status" => 1 ],
            [ "id" => 309, "state_id" => 26, "name" => "HELENA", "slug" => "helena", "short_code" => "", "status" => 1 ],
            [ "id" => 310, "state_id" => 26, "name" => "MISSOULA", "slug" => "missoula", "short_code" => "", "status" => 1 ],
            [ "id" => 311, "state_id" => 27, "name" => "ASHEVILLE", "slug" => "asheville", "short_code" => "", "status" => 1 ],
            [ "id" => 312, "state_id" => 27, "name" => "CHARLOTTE", "slug" => "charlotte", "short_code" => "", "status" => 1 ],
            [ "id" => 313, "state_id" => 27, "name" => "CHINA GROVE", "slug" => "china-grove", "short_code" => "", "status" => 1 ],
            [ "id" => 314, "state_id" => 27, "name" => "CONCORD", "slug" => "concord", "short_code" => "", "status" => 1 ],
            [ "id" => 315, "state_id" => 27, "name" => "CASTLE HAYNE", "slug" => "castle-hayne", "short_code" => "", "status" => 1 ],
            [ "id" => 316, "state_id" => 27, "name" => "CLAYTON", "slug" => "clayton", "short_code" => "", "status" => 1 ],
            [ "id" => 317, "state_id" => 27, "name" => "DUNN", "slug" => "dunn", "short_code" => "", "status" => 1 ],
            [ "id" => 318, "state_id" => 27, "name" => "FLECHER", "slug" => "flecher", "short_code" => "", "status" => 1 ],
            [ "id" => 319, "state_id" => 27, "name" => "GRAHAM ", "slug" => "graham", "short_code" => "", "status" => 1 ],
            [ "id" => 320, "state_id" => 27, "name" => "GREENSBORO", "slug" => "greensboro", "short_code" => "", "status" => 1 ],
            [ "id" => 321, "state_id" => 27, "name" => "LUMBERTON", "slug" => "lumberton", "short_code" => "", "status" => 1 ],
            [ "id" => 322, "state_id" => 27, "name" => "MEBANE", "slug" => "mebane", "short_code" => "", "status" => 1 ],
            [ "id" => 323, "state_id" => 27, "name" => "MOCKSVILLE", "slug" => "mocksville", "short_code" => "", "status" => 1 ],
            [ "id" => 324, "state_id" => 27, "name" => "RALEIGH", "slug" => "raleigh", "short_code" => "", "status" => 1 ],
            [ "id" => 325, "state_id" => 27, "name" => "STATESVILLE", "slug" => "statesville", "short_code" => "", "status" => 1 ],
            [ "id" => 326, "state_id" => 27, "name" => "WILMINGTON", "slug" => "wilmington-2", "short_code" => "", "status" => 1 ],
            [ "id" => 327, "state_id" => 28, "name" => "FARGO", "slug" => "fargo", "short_code" => "", "status" => 1 ],
            [ "id" => 328, "state_id" => 28, "name" => "OMAHA", "slug" => "omaha", "short_code" => "", "status" => 1 ],
            [ "id" => 329, "state_id" => 28, "name" => "BISMARCK", "slug" => "bismarck", "short_code" => "", "status" => 1 ],
            [ "id" => 330, "state_id" => 29, "name" => "GREENWOOD", "slug" => "greenwood-3", "short_code" => "", "status" => 1 ],
            [ "id" => 331, "state_id" => 29, "name" => "LINCOLN", "slug" => "lincoln-3", "short_code" => "", "status" => 1 ],
            [ "id" => 332, "state_id" => 29, "name" => "SPRINGFIELD", "slug" => "springfield-3", "short_code" => "", "status" => 1 ],
            [ "id" => 333, "state_id" => 30, "name" => "AVENEL", "slug" => "avenel", "short_code" => "", "status" => 1 ],
            [ "id" => 334, "state_id" => 30, "name" => "BAYONNE", "slug" => "bayonne", "short_code" => "", "status" => 1 ],
            [ "id" => 335, "state_id" => 30, "name" => "BORDENTOWN", "slug" => "bordentown", "short_code" => "", "status" => 1 ],
            [ "id" => 336, "state_id" => 30, "name" => "CARTRET", "slug" => "cartret", "short_code" => "", "status" => 1 ],
            [ "id" => 337, "state_id" => 30, "name" => "CENTRAL NEW JERSEY", "slug" => "central-new-jersey", "short_code" => "", "status" => 1 ],
            [ "id" => 338, "state_id" => 30, "name" => "FAIRFIELD", "slug" => "fairfield", "short_code" => "", "status" => 1 ],
            [ "id" => 339, "state_id" => 30, "name" => "HILLSBOROUGH", "slug" => "hillsborough", "short_code" => "", "status" => 1 ],
            [ "id" => 340, "state_id" => 30, "name" => "GLASSBORO EAST", "slug" => "glassboro-east", "short_code" => "", "status" => 1 ],
            [ "id" => 341, "state_id" => 30, "name" => "GLASSBORO WEST", "slug" => "glassboro-west", "short_code" => "", "status" => 1 ],
            [ "id" => 342, "state_id" => 30, "name" => "MANVILLE", "slug" => "manville", "short_code" => "", "status" => 1 ],
            [ "id" => 343, "state_id" => 30, "name" => "MORGAN VILLE", "slug" => "morgan-ville", "short_code" => "", "status" => 1 ],
            [ "id" => 344, "state_id" => 30, "name" => "NEWARK", "slug" => "newark", "short_code" => "", "status" => 1 ],
            [ "id" => 345, "state_id" => 30, "name" => "NORTHERN NEW JERSEY", "slug" => "northern-new-jersey", "short_code" => "", "status" => 1 ],
            [ "id" => 346, "state_id" => 30, "name" => "ROSELLE", "slug" => "roselle", "short_code" => "", "status" => 1 ],
            [ "id" => 347, "state_id" => 30, "name" => "SOMERVILLE", "slug" => "somerville", "short_code" => "", "status" => 1 ],
            [ "id" => 348, "state_id" => 30, "name" => "SOUTHERN NEW JERSEY", "slug" => "southern-new-jersey", "short_code" => "", "status" => 1 ],
            [ "id" => 349, "state_id" => 30, "name" => "TURNERSVILLE", "slug" => "turnersville", "short_code" => "", "status" => 1 ],
            [ "id" => 350, "state_id" => 30, "name" => "TURNERSVILLE", "slug" => "turnersville-2", "short_code" => "", "status" => 1 ],
            [ "id" => 351, "state_id" => 30, "name" => "TRENTON", "slug" => "trenton", "short_code" => "", "status" => 1 ],
            [ "id" => 352, "state_id" => 30, "name" => "WINDSOR", "slug" => "windsor", "short_code" => "", "status" => 1 ],
            [ "id" => 353, "state_id" => 31, "name" => "CANDIA", "slug" => "candia", "short_code" => "", "status" => 1 ],
            [ "id" => 354, "state_id" => 31, "name" => "MANCHESTER", "slug" => "manchester", "short_code" => "", "status" => 1 ],
            [ "id" => 355, "state_id" => 31, "name" => "MANCHESTER", "slug" => "manchester-2", "short_code" => "", "status" => 1 ],
            [ "id" => 356, "state_id" => 31, "name" => "SALEM ", "slug" => "salem", "short_code" => "", "status" => 1 ],
            [ "id" => 357, "state_id" => 31, "name" => "WEBSTER", "slug" => "webster", "short_code" => "", "status" => 1 ],
            [ "id" => 358, "state_id" => 32, "name" => "ALBUQUERQUE", "slug" => "albuquerque", "short_code" => "", "status" => 1 ],
            [ "id" => 359, "state_id" => 33, "name" => "HENDERSON", "slug" => "henderson", "short_code" => "", "status" => 1 ],
            [ "id" => 360, "state_id" => 40, "name" => "LEXINGTON", "slug" => "lexington-2", "short_code" => "", "status" => 1 ],
            [ "id" => 361, "state_id" => 33, "name" => "LAS VEGAS", "slug" => "las-vegas", "short_code" => "", "status" => 1 ],
            [ "id" => 362, "state_id" => 40, "name" => "RAVENEL", "slug" => "ravenel", "short_code" => "", "status" => 1 ],
            [ "id" => 363, "state_id" => 33, "name" => "MCCARAN", "slug" => "mccaran", "short_code" => "", "status" => 1 ],
            [ "id" => 364, "state_id" => 33, "name" => "NORTH LAS VEGAS", "slug" => "north-las-vegas", "short_code" => "", "status" => 1 ],
            [ "id" => 365, "state_id" => 33, "name" => "RENO", "slug" => "reno", "short_code" => "", "status" => 1 ],
            [ "id" => 366, "state_id" => 40, "name" => "SPARTENBURGH", "slug" => "spartenburgh", "short_code" => "", "status" => 1 ],
            [ "id" => 367, "state_id" => 34, "name" => "ALBANY", "slug" => "albany", "short_code" => "", "status" => 1 ],
            [ "id" => 368, "state_id" => 34, "name" => "AKRON", "slug" => "akron", "short_code" => "", "status" => 1 ],
            [ "id" => 369, "state_id" => 34, "name" => "BUFFALO", "slug" => "buffalo", "short_code" => "", "status" => 1 ],
            [ "id" => 370, "state_id" => 34, "name" => "BERGAN", "slug" => "bergan", "short_code" => "", "status" => 1 ],
            [ "id" => 371, "state_id" => 34, "name" => "BROCTON", "slug" => "brocton", "short_code" => "", "status" => 1 ],
            [ "id" => 372, "state_id" => 34, "name" => "BROOKHAVEN", "slug" => "brookhaven", "short_code" => "", "status" => 1 ],
            [ "id" => 373, "state_id" => 34, "name" => "CICERO", "slug" => "cicero", "short_code" => "", "status" => 1 ],
            [ "id" => 374, "state_id" => 34, "name" => "CENTRAL SQUARE", "slug" => "central-square", "short_code" => "", "status" => 1 ],
            [ "id" => 375, "state_id" => 34, "name" => "LONG ISLAND", "slug" => "long-island", "short_code" => "", "status" => 1 ],
            [ "id" => 376, "state_id" => 34, "name" => "LE ROY", "slug" => "le-roy", "short_code" => "", "status" => 1 ],
            [ "id" => 377, "state_id" => 34, "name" => "MALBORO", "slug" => "malboro", "short_code" => "", "status" => 1 ],
            [ "id" => 378, "state_id" => 34, "name" => "MEDFORD", "slug" => "medford", "short_code" => "", "status" => 1 ],
            [ "id" => 379, "state_id" => 43, "name" => "ABILENE", "slug" => "abilene", "short_code" => "", "status" => 1 ],
            [ "id" => 380, "state_id" => 34, "name" => "NEWBURGH", "slug" => "newburgh", "short_code" => "", "status" => 1 ],
            [ "id" => 381, "state_id" => 34, "name" => "ROCK TAVERN", "slug" => "rock-tavern", "short_code" => "", "status" => 1 ],
            [ "id" => 382, "state_id" => 34, "name" => "ROCHESTER", "slug" => "rochester", "short_code" => "", "status" => 1 ],
            [ "id" => 383, "state_id" => 34, "name" => "SHCHENECTADY", "slug" => "shchenectady", "short_code" => "", "status" => 1 ],
            [ "id" => 384, "state_id" => 34, "name" => "SYRACUSE", "slug" => "syracuse", "short_code" => "", "status" => 1 ],
            [ "id" => 385, "state_id" => 34, "name" => "YAPHANK", "slug" => "yaphank", "short_code" => "", "status" => 1 ],
            [ "id" => 386, "state_id" => 35, "name" => "AKRON CANTON", "slug" => "akron-canton", "short_code" => "", "status" => 1 ],
            [ "id" => 387, "state_id" => 35, "name" => "CICNCINNATI", "slug" => "cicncinnati", "short_code" => "", "status" => 1 ],
            [ "id" => 388, "state_id" => 35, "name" => "CLEVELAND", "slug" => "cleveland", "short_code" => "", "status" => 1 ],
            [ "id" => 389, "state_id" => 35, "name" => "CLEVELAND EAST", "slug" => "cleveland-east", "short_code" => "", "status" => 1 ],
            [ "id" => 390, "state_id" => 35, "name" => "CLEVELAND WEST", "slug" => "cleveland-west", "short_code" => "", "status" => 1 ],
            [ "id" => 391, "state_id" => 35, "name" => "COLUMBUS", "slug" => "columbus-3", "short_code" => "", "status" => 1 ],
            [ "id" => 392, "state_id" => 35, "name" => "COLUMBIA STATION", "slug" => "columbia-station", "short_code" => "", "status" => 1 ],
            [ "id" => 393, "state_id" => 35, "name" => "DAYTON", "slug" => "dayton", "short_code" => "", "status" => 1 ],
            [ "id" => 394, "state_id" => 35, "name" => "FRANKLIN", "slug" => "franklin", "short_code" => "", "status" => 1 ],
            [ "id" => 395, "state_id" => 35, "name" => "GROVECITY", "slug" => "grovecity", "short_code" => "", "status" => 1 ],
            [ "id" => 396, "state_id" => 35, "name" => "HAMILTON", "slug" => "hamilton", "short_code" => "", "status" => 1 ],
            [ "id" => 397, "state_id" => 35, "name" => "LORAIN", "slug" => "lorain", "short_code" => "", "status" => 1 ],
            [ "id" => 398, "state_id" => 35, "name" => "MORAINE", "slug" => "moraine", "short_code" => "", "status" => 1 ],
            [ "id" => 399, "state_id" => 35, "name" => "NEW PHILALDELPHIA", "slug" => "new-philaldelphia", "short_code" => "", "status" => 1 ],
            [ "id" => 400, "state_id" => 35, "name" => "NORTHFIELD", "slug" => "northfield", "short_code" => "", "status" => 1 ],
            [ "id" => 401, "state_id" => 35, "name" => "VERMILION", "slug" => "vermilion", "short_code" => "", "status" => 1 ],
            [ "id" => 402, "state_id" => 35, "name" => "WEST CHESTER", "slug" => "west-chester", "short_code" => "", "status" => 1 ],
            [ "id" => 403, "state_id" => 36, "name" => "OKLAHOMA CITY", "slug" => "oklahoma-city", "short_code" => "", "status" => 1 ],
            [ "id" => 404, "state_id" => 36, "name" => "SAPULPA", "slug" => "sapulpa", "short_code" => "", "status" => 1 ],
            [ "id" => 405, "state_id" => 36, "name" => "TULSA", "slug" => "tulsa", "short_code" => "", "status" => 1 ],
            [ "id" => 406, "state_id" => 37, "name" => "EUGENE", "slug" => "eugene", "short_code" => "", "status" => 1 ],
            [ "id" => 407, "state_id" => 37, "name" => "PORTLAND", "slug" => "portland-2", "short_code" => "", "status" => 1 ],
            [ "id" => 408, "state_id" => 37, "name" => "PORTLAND NORTH", "slug" => "portland-north", "short_code" => "", "status" => 1 ],
            [ "id" => 409, "state_id" => 37, "name" => "PORTLAND SOUTH", "slug" => "portland-south", "short_code" => "", "status" => 1 ],
            [ "id" => 410, "state_id" => 37, "name" => "PORTLAND WEST", "slug" => "portland-west", "short_code" => "", "status" => 1 ],
            [ "id" => 411, "state_id" => 37, "name" => "WOODBURN", "slug" => "woodburn", "short_code" => "", "status" => 1 ],
            [ "id" => 412, "state_id" => 38, "name" => "ADAMSBURGH", "slug" => "adamsburgh", "short_code" => "", "status" => 1 ],
            [ "id" => 413, "state_id" => 38, "name" => "ALTOONA", "slug" => "altoona", "short_code" => "", "status" => 1 ],
            [ "id" => 414, "state_id" => 38, "name" => "ALIQUIPPA", "slug" => "aliquippa", "short_code" => "", "status" => 1 ],
            [ "id" => 415, "state_id" => 38, "name" => "BRIDGEPORT", "slug" => "bridgeport", "short_code" => "", "status" => 1 ],
            [ "id" => 416, "state_id" => 38, "name" => "CHAMBERSBURG", "slug" => "chambersburg", "short_code" => "", "status" => 1 ],
            [ "id" => 417, "state_id" => 38, "name" => "CHALFONT", "slug" => "chalfont", "short_code" => "", "status" => 1 ],
            [ "id" => 418, "state_id" => 38, "name" => "CONSHOHOCKEN", "slug" => "conshohocken", "short_code" => "", "status" => 1 ],
            [ "id" => 419, "state_id" => 38, "name" => "DURYEA", "slug" => "duryea", "short_code" => "", "status" => 1 ],
            [ "id" => 420, "state_id" => 38, "name" => "ERIE", "slug" => "erie", "short_code" => "", "status" => 1 ],
            [ "id" => 421, "state_id" => 38, "name" => "EBENSBURGH", "slug" => "ebensburgh", "short_code" => "", "status" => 1 ],
            [ "id" => 422, "state_id" => 38, "name" => "ELLWOOD CITY", "slug" => "ellwood-city", "short_code" => "", "status" => 1 ],
            [ "id" => 423, "state_id" => 38, "name" => "EAST FREEDOM", "slug" => "east-freedom", "short_code" => "", "status" => 1 ],
            [ "id" => 424, "state_id" => 38, "name" => "GARLAND", "slug" => "garland", "short_code" => "", "status" => 1 ],
            [ "id" => 425, "state_id" => 38, "name" => "GIBSONIA", "slug" => "gibsonia", "short_code" => "", "status" => 1 ],
            [ "id" => 426, "state_id" => 38, "name" => "GRANTVILLE", "slug" => "grantville", "short_code" => "", "status" => 1 ],
            [ "id" => 427, "state_id" => 38, "name" => "HATFIELD", "slug" => "hatfield", "short_code" => "", "status" => 1 ],
            [ "id" => 428, "state_id" => 38, "name" => "HARRISBURGH", "slug" => "harrisburgh", "short_code" => "", "status" => 1 ],
            [ "id" => 429, "state_id" => 38, "name" => "MANHEIM", "slug" => "manheim", "short_code" => "", "status" => 1 ],
            [ "id" => 430, "state_id" => 38, "name" => "MERCER", "slug" => "mercer", "short_code" => "", "status" => 1 ],
            [ "id" => 431, "state_id" => 38, "name" => "PHILADELPHIA", "slug" => "philadelphia", "short_code" => "", "status" => 1 ],
            [ "id" => 432, "state_id" => 38, "name" => "PHILADELPHIA EAST", "slug" => "philadelphia-east", "short_code" => "", "status" => 1 ],
            [ "id" => 433, "state_id" => 38, "name" => "PITTSBURG", "slug" => "pittsburg", "short_code" => "", "status" => 1 ],
            [ "id" => 434, "state_id" => 38, "name" => "PITTSBURG NORTH", "slug" => "pittsburg-north", "short_code" => "", "status" => 1 ],
            [ "id" => 435, "state_id" => 38, "name" => "PITTSBURG SOUTH", "slug" => "pittsburg-south", "short_code" => "", "status" => 1 ],
            [ "id" => 436, "state_id" => 38, "name" => "PITTSTON", "slug" => "pittston", "short_code" => "", "status" => 1 ],
            [ "id" => 437, "state_id" => 38, "name" => "SCRANTON", "slug" => "scranton", "short_code" => "", "status" => 1 ],
            [ "id" => 438, "state_id" => 38, "name" => "WEST MIFFLIN", "slug" => "west-mifflin", "short_code" => "", "status" => 1 ],
            [ "id" => 439, "state_id" => 38, "name" => "WASHINGTON  ", "slug" => "washington", "short_code" => "", "status" => 1 ],
            [ "id" => 440, "state_id" => 38, "name" => "YORK", "slug" => "york", "short_code" => "", "status" => 1 ],
            [ "id" => 441, "state_id" => 38, "name" => "YORK HAVEN", "slug" => "york-haven", "short_code" => "", "status" => 1 ],
            [ "id" => 442, "state_id" => 38, "name" => "YORK SPRINGS", "slug" => "york-springs", "short_code" => "", "status" => 1 ],
            [ "id" => 443, "state_id" => 39, "name" => "EXETER", "slug" => "exeter", "short_code" => "", "status" => 1 ],
            [ "id" => 444, "state_id" => 39, "name" => "PROVIDENCE", "slug" => "providence", "short_code" => "", "status" => 1 ],
            [ "id" => 445, "state_id" => 39, "name" => "RIVERSIDE", "slug" => "riverside-2", "short_code" => "", "status" => 1 ],
            [ "id" => 446, "state_id" => 40, "name" => "ASHEVILLE", "slug" => "asheville-2", "short_code" => "", "status" => 1 ],
            [ "id" => 447, "state_id" => 40, "name" => "CHARLESTON", "slug" => "charleston", "short_code" => "", "status" => 1 ],
            [ "id" => 448, "state_id" => 40, "name" => "COLUMBIA", "slug" => "columbia-2", "short_code" => "", "status" => 1 ],
            [ "id" => 449, "state_id" => 40, "name" => "DARLINGTON", "slug" => "darlington", "short_code" => "", "status" => 1 ],
            [ "id" => 450, "state_id" => 40, "name" => "GREENVILLE", "slug" => "greenville", "short_code" => "", "status" => 1 ],
            [ "id" => 451, "state_id" => 40, "name" => "GASTON", "slug" => "gaston", "short_code" => "", "status" => 1 ],
            [ "id" => 452, "state_id" => 40, "name" => "GREER", "slug" => "greer", "short_code" => "", "status" => 1 ],
            [ "id" => 453, "state_id" => 40, "name" => "SIMPSONVILLE", "slug" => "simpsonville", "short_code" => "", "status" => 1 ],
            [ "id" => 454, "state_id" => 40, "name" => "WILLIAMSTON", "slug" => "williamston", "short_code" => "", "status" => 1 ],
            [ "id" => 455, "state_id" => 41, "name" => "RAPID CITY", "slug" => "rapid-city", "short_code" => "", "status" => 1 ],
            [ "id" => 456, "state_id" => 41, "name" => "SIOUX FALLS", "slug" => "sioux-falls", "short_code" => "", "status" => 1 ],
            [ "id" => 457, "state_id" => 42, "name" => "CHATTANOOGA", "slug" => "chattanooga", "short_code" => "", "status" => 1 ],
            [ "id" => 458, "state_id" => 42, "name" => "FALL BRANCH", "slug" => "fall-branch", "short_code" => "", "status" => 1 ],
            [ "id" => 459, "state_id" => 42, "name" => "KNOXVILLE ", "slug" => "knoxville", "short_code" => "", "status" => 1 ],
            [ "id" => 460, "state_id" => 42, "name" => "LENOIR CITY", "slug" => "lenoir-city", "short_code" => "", "status" => 1 ],
            [ "id" => 461, "state_id" => 42, "name" => "LEBANON", "slug" => "lebanon", "short_code" => "", "status" => 1 ],
            [ "id" => 462, "state_id" => 42, "name" => "MEMPHIS ", "slug" => "memphis", "short_code" => "", "status" => 1 ],
            [ "id" => 463, "state_id" => 42, "name" => "MOUNT JULIET", "slug" => "mount-juliet", "short_code" => "", "status" => 1 ],
            [ "id" => 464, "state_id" => 42, "name" => "MADISON VILLE", "slug" => "madison-ville", "short_code" => "", "status" => 1 ],
            [ "id" => 465, "state_id" => 42, "name" => "NASHVILLE ", "slug" => "nashville", "short_code" => "", "status" => 1 ],
            [ "id" => 466, "state_id" => 43, "name" => "AMARILO", "slug" => "amarilo", "short_code" => "", "status" => 1 ],
            [ "id" => 467, "state_id" => 43, "name" => "AUSTIN ", "slug" => "austin", "short_code" => "", "status" => 1 ],
            [ "id" => 468, "state_id" => 43, "name" => "ANDREWS", "slug" => "andrews", "short_code" => "", "status" => 1 ],
            [ "id" => 469, "state_id" => 43, "name" => "ANTHONY", "slug" => "anthony", "short_code" => "", "status" => 1 ],
            [ "id" => 470, "state_id" => 43, "name" => "CORPUS CHRISTI ", "slug" => "corpus-christi", "short_code" => "", "status" => 1 ],
            [ "id" => 471, "state_id" => 43, "name" => "DALE", "slug" => "dale", "short_code" => "", "status" => 1 ],
            [ "id" => 472, "state_id" => 43, "name" => "DALLAS ", "slug" => "dallas", "short_code" => "", "status" => 1 ],
            [ "id" => 473, "state_id" => 43, "name" => "DONA", "slug" => "dona", "short_code" => "", "status" => 1 ],
            [ "id" => 474, "state_id" => 43, "name" => "HOUSTON", "slug" => "houston", "short_code" => "HOU", "status" => 1 ],
            [ "id" => 475, "state_id" => 43, "name" => "DALLAS SOUTH", "slug" => "dallas-south", "short_code" => "", "status" => 1 ],
            [ "id" => 476, "state_id" => 43, "name" => "EULESS", "slug" => "euless", "short_code" => "", "status" => 1 ],
            [ "id" => 477, "state_id" => 43, "name" => "EL PASO ", "slug" => "el-paso", "short_code" => "", "status" => 1 ],
            [ "id" => 478, "state_id" => 43, "name" => "FORT WORTH ", "slug" => "fort-worth", "short_code" => "", "status" => 1 ],
            [ "id" => 479, "state_id" => 43, "name" => "GARLAND", "slug" => "garland-2", "short_code" => "", "status" => 1 ],
            [ "id" => 480, "state_id" => 43, "name" => "GRAND PRAIRE", "slug" => "grand-praire", "short_code" => "", "status" => 1 ],
            [ "id" => 481, "state_id" => 43, "name" => "HASLET", "slug" => "haslet", "short_code" => "", "status" => 1 ],
            [ "id" => 482, "state_id" => 43, "name" => "HURST", "slug" => "hurst", "short_code" => "", "status" => 1 ],
            [ "id" => 483, "state_id" => 43, "name" => "HUTCHINS", "slug" => "hutchins", "short_code" => "", "status" => 1 ],
            [ "id" => 484, "state_id" => 45, "name" => "SANDSTON", "slug" => "sandston", "short_code" => "", "status" => 1 ],
            [ "id" => 485, "state_id" => 43, "name" => "JUSTIN", "slug" => "justin", "short_code" => "", "status" => 1 ],
            [ "id" => 486, "state_id" => 43, "name" => "LONGVIEW ", "slug" => "longview", "short_code" => "", "status" => 1 ],
            [ "id" => 487, "state_id" => 43, "name" => "WACO", "slug" => "waco", "short_code" => "", "status" => 1 ],
            [ "id" => 488, "state_id" => 43, "name" => "LUBBOCK ", "slug" => "lubbock", "short_code" => "", "status" => 1 ],
            [ "id" => 489, "state_id" => 43, "name" => "LUFKIN", "slug" => "lufkin", "short_code" => "", "status" => 1 ],
            [ "id" => 490, "state_id" => 43, "name" => "MERCEDES", "slug" => "mercedes", "short_code" => "", "status" => 1 ],
            [ "id" => 491, "state_id" => 43, "name" => "MCALLEN ", "slug" => "mcallen", "short_code" => "", "status" => 1 ],
            [ "id" => 492, "state_id" => 43, "name" => "NEW BRAUNFELS", "slug" => "new-braunfels", "short_code" => "", "status" => 1 ],
            [ "id" => 493, "state_id" => 43, "name" => "ODESSA", "slug" => "odessa", "short_code" => "", "status" => 1 ],
            [ "id" => 494, "state_id" => 43, "name" => "PERMIAN BASIN ", "slug" => "permian-basin", "short_code" => "", "status" => 1 ],
            [ "id" => 495, "state_id" => 43, "name" => "SAN ANTONIO ", "slug" => "san-antonio", "short_code" => "", "status" => 1 ],
            [ "id" => 496, "state_id" => 43, "name" => "TEMPLE  ", "slug" => "temple", "short_code" => "", "status" => 1 ],
            [ "id" => 497, "state_id" => 43, "name" => "WILMER", "slug" => "wilmer", "short_code" => "", "status" => 1 ],
            [ "id" => 498, "state_id" => 52, "name" => "DUBAI", "slug" => "dubai", "short_code" => "DXB", "status" => 1 ],
            [ "id" => 499, "state_id" => 44, "name" => "FARR WEST", "slug" => "farr-west", "short_code" => "", "status" => 1 ],
            [ "id" => 500, "state_id" => 44, "name" => "NORTH SALT LAKE", "slug" => "north-salt-lake", "short_code" => "", "status" => 1 ],
            [ "id" => 501, "state_id" => 44, "name" => "SALT LAKE CITY ", "slug" => "salt-lake-city", "short_code" => "", "status" => 1 ],
            [ "id" => 502, "state_id" => 44, "name" => "OGDEN", "slug" => "ogden", "short_code" => "", "status" => 1 ],
            [ "id" => 503, "state_id" => 44, "name" => "WEST VALLEY", "slug" => "west-valley", "short_code" => "", "status" => 1 ],
            [ "id" => 504, "state_id" => 44, "name" => "WOOD CROSS", "slug" => "wood-cross", "short_code" => "", "status" => 1 ],
            [ "id" => 505, "state_id" => 45, "name" => "ASHLAND", "slug" => "ashland-2", "short_code" => "", "status" => 1 ],
            [ "id" => 506, "state_id" => 45, "name" => "CULPERER", "slug" => "culperer", "short_code" => "", "status" => 1 ],
            [ "id" => 507, "state_id" => 45, "name" => "CHATHAM", "slug" => "chatham", "short_code" => "", "status" => 1 ],
            [ "id" => 508, "state_id" => 45, "name" => "DULLES", "slug" => "dulles", "short_code" => "", "status" => 1 ],
            [ "id" => 509, "state_id" => 45, "name" => "DANVILLE ", "slug" => "danville", "short_code" => "", "status" => 1 ],
            [ "id" => 510, "state_id" => 45, "name" => "FREDRICKSBURGH", "slug" => "fredricksburgh", "short_code" => "", "status" => 1 ],
            [ "id" => 511, "state_id" => 45, "name" => "HARRISONBURGH", "slug" => "harrisonburgh", "short_code" => "", "status" => 1 ],
            [ "id" => 512, "state_id" => 45, "name" => "HAMPTON ", "slug" => "hampton", "short_code" => "", "status" => 1 ],
            [ "id" => 513, "state_id" => 45, "name" => "KING GEORGE ", "slug" => "king-george", "short_code" => "", "status" => 1 ],
            [ "id" => 514, "state_id" => 45, "name" => "MADISON HEIGHTS ", "slug" => "madison-heights", "short_code" => "", "status" => 1 ],
            [ "id" => 515, "state_id" => 45, "name" => "NORTHERN VIRGINIA ", "slug" => "northern-virginia", "short_code" => "", "status" => 1 ],
            [ "id" => 516, "state_id" => 45, "name" => "PULASKI", "slug" => "pulaski", "short_code" => "", "status" => 1 ],
            [ "id" => 517, "state_id" => 45, "name" => "RICHMOND", "slug" => "richmond", "short_code" => "", "status" => 1 ],
            [ "id" => 518, "state_id" => 45, "name" => "RICHMOND EAST ", "slug" => "richmond-east", "short_code" => "", "status" => 1 ],
            [ "id" => 519, "state_id" => 45, "name" => "RUSTBURG ", "slug" => "rustburg", "short_code" => "", "status" => 1 ],
            [ "id" => 520, "state_id" => 45, "name" => "SAFFOLK ", "slug" => "saffolk", "short_code" => "", "status" => 1 ],
            [ "id" => 521, "state_id" => 45, "name" => "SALEM ", "slug" => "salem-2", "short_code" => "", "status" => 1 ],
            [ "id" => 522, "state_id" => 45, "name" => "TIDEWATER", "slug" => "tidewater", "short_code" => "", "status" => 1 ],
            [ "id" => 523, "state_id" => 45, "name" => "YORKTOWN", "slug" => "yorktown", "short_code" => "", "status" => 1 ],
            [ "id" => 524, "state_id" => 46, "name" => "ESSEX", "slug" => "essex", "short_code" => "", "status" => 1 ],
            [ "id" => 525, "state_id" => 46, "name" => "FAIRHAVEN", "slug" => "fairhaven", "short_code" => "", "status" => 1 ],
            [ "id" => 526, "state_id" => 46, "name" => "ORLEANS", "slug" => "orleans", "short_code" => "", "status" => 1 ],
            [ "id" => 527, "state_id" => 47, "name" => "AIRWAY", "slug" => "airway", "short_code" => "", "status" => 1 ],
            [ "id" => 528, "state_id" => 47, "name" => "ARLINGTON", "slug" => "arlington", "short_code" => "", "status" => 1 ],
            [ "id" => 529, "state_id" => 47, "name" => "GRAHAM ", "slug" => "graham-2", "short_code" => "", "status" => 1 ],
            [ "id" => 530, "state_id" => 47, "name" => "NORTH SEATTLE ", "slug" => "north-seattle", "short_code" => "", "status" => 1 ],
            [ "id" => 531, "state_id" => 47, "name" => "PUYALLUP", "slug" => "puyallup", "short_code" => "", "status" => 1 ],
            [ "id" => 532, "state_id" => 47, "name" => "PASCO ", "slug" => "pasco", "short_code" => "", "status" => 1 ],
            [ "id" => 533, "state_id" => 47, "name" => "SPOKANE ", "slug" => "spokane", "short_code" => "", "status" => 1 ],
            [ "id" => 534, "state_id" => 47, "name" => "SPOKANE VALLEY", "slug" => "spokane-valley", "short_code" => "", "status" => 1 ],
            [ "id" => 535, "state_id" => 38, "name" => "PENNSBURG", "slug" => "pennsburg", "short_code" => "", "status" => 1 ],
            [ "id" => 536, "state_id" => 48, "name" => "APPLETON", "slug" => "appleton", "short_code" => "", "status" => 1 ],
            [ "id" => 537, "state_id" => 48, "name" => "CALEDONIA", "slug" => "caledonia", "short_code" => "", "status" => 1 ],
            [ "id" => 538, "state_id" => 48, "name" => "MILWAUKEE", "slug" => "milwaukee", "short_code" => "", "status" => 1 ],
            [ "id" => 539, "state_id" => 48, "name" => "MADISON", "slug" => "madison", "short_code" => "", "status" => 1 ],
            [ "id" => 540, "state_id" => 48, "name" => "PORTAGE", "slug" => "portage", "short_code" => "", "status" => 1 ],
            [ "id" => 541, "state_id" => 48, "name" => "SUSSEX", "slug" => "sussex", "short_code" => "", "status" => 1 ],
            [ "id" => 542, "state_id" => 49, "name" => "BUKHANNON ", "slug" => "bukhannon", "short_code" => "", "status" => 1 ],
            [ "id" => 543, "state_id" => 49, "name" => "CHARLESTON ", "slug" => "charleston-2", "short_code" => "", "status" => 1 ],
            [ "id" => 544, "state_id" => 49, "name" => "HURRYCANE", "slug" => "hurrycane", "short_code" => "", "status" => 1 ],
            [ "id" => 545, "state_id" => 49, "name" => "SHADY SPRINGS ", "slug" => "shady-springs", "short_code" => "", "status" => 1 ],
            [ "id" => 546, "state_id" => 50, "name" => "SUNDANCE ", "slug" => "sundance", "short_code" => "", "status" => 1 ],
            [ "id" => 547, "state_id" => 50, "name" => "CASPER", "slug" => "casper", "short_code" => "", "status" => 1 ],
            [ "id" => 548, "state_id" => 50, "name" => "test2", "slug" => "test2", "short_code" => "", "status" => 1 ],
            [ "id" => 549, "state_id" => 30, "name" => "NEW JERSEY", "slug" => "new-jersey", "short_code" => "NJ", "status" => 1 ],
            [ "id" => 550, "state_id" => 54, "name" => "HAMILTON IMPACT", "slug" => "hamilton-impact", "short_code" => "ON", "status" => 1 ],
            [ "id" => 551, "state_id" => 54, "name" => "OSHAWA COPART", "slug" => "oshawa-copart", "short_code" => "ON", "status" => 1 ],
            [ "id" => 552, "state_id" => 54, "name" => "STOUFFVILLE COPART", "slug" => "stouffville-copart", "short_code" => "ON", "status" => 1 ],
            [ "id" => 553, "state_id" => 54, "name" => "COUTICE COPART", "slug" => "coutice-copart", "short_code" => "ON", "status" => 1 ],
            [ "id" => 554, "state_id" => 54, "name" => "LONDON IMPACT", "slug" => "london-impact", "short_code" => "UK", "status" => 1 ],
            [ "id" => 555, "state_id" => 54, "name" => "SUDBURRY IMPACT", "slug" => "sudburry-impact", "short_code" => "ON", "status" => 1 ],
            [ "id" => 556, "state_id" => 55, "name" => "OTTAWA IMPACT", "slug" => "ottawa-impact", "short_code" => "ON", "status" => 1 ],
            [ "id" => 557, "state_id" => 55, "name" => "GRAND RIVERE QC", "slug" => "grand-rivere-qc", "short_code" => "QC", "status" => 1 ],
            [ "id" => 558, "state_id" => 55, "name" => "MONTREAL IMPACT", "slug" => "montreal-impact", "short_code" => "QC", "status" => 1 ],
            [ "id" => 559, "state_id" => 55, "name" => "MONTREAL COPART", "slug" => "montreal-copart", "short_code" => "QC", "status" => 1 ],
            [ "id" => 560, "state_id" => 56, "name" => "ENFIELD", "slug" => "enfield", "short_code" => "NS", "status" => 1 ],
            [ "id" => 561, "state_id" => 56, "name" => "MONCTION", "slug" => "monction", "short_code" => "NB", "status" => 1 ],
            [ "id" => 562, "state_id" => 56, "name" => "COW BOY", "slug" => "cow-boy", "short_code" => "ON", "status" => 1 ],
            [ "id" => 563, "state_id" => 58, "name" => "CALGARY IMPACT", "slug" => "calgary-impact", "short_code" => "AB", "status" => 1 ],
            [ "id" => 564, "state_id" => 57, "name" => "EDMONTON IMPACT", "slug" => "edmonton-impact", "short_code" => "AB", "status" => 1 ],
            [ "id" => 565, "state_id" => 54, "name" => "BRITISH COLUMBIA", "slug" => "british-columbia", "short_code" => "ON", "status" => 0 ],
            [ "id" => 566, "state_id" => 58, "name" => "BRITISH COLUMBIA", "slug" => "british-columbia-2", "short_code" => "AB", "status" => 1 ],
            [ "id" => 567, "state_id" => 73, "name" => "Islam Qalla", "slug" => "islam-qalla", "short_code" => "", "status" => 1 ],
            [ "id" => 568, "state_id" => 70, "name" => "Ashgabat", "slug" => "ashgabat", "short_code" => "", "status" => 1 ],
            [ "id" => 569, "state_id" => 71, "name" => "Charjov", "slug" => "charjov", "short_code" => "", "status" => 1 ],
            [ "id" => 570, "state_id" => 69, "name" => "Mary", "slug" => "mary", "short_code" => "", "status" => 1 ],
            [ "id" => 571, "state_id" => 72, "name" => "Sarakhs", "slug" => "sarakhs", "short_code" => "", "status" => 1 ],
            [ "id" => 572, "state_id" => 75, "name" => "Bandar Linga", "slug" => "bandar-linga", "short_code" => "", "status" => 1 ],
            [ "id" => 573, "state_id" => 74, "name" => "Bandar Bas", "slug" => "bandar-bas", "short_code" => "", "status" => 1 ],
            [ "id" => 574, "state_id" => 76, "name" => "VANCOUVER", "slug" => "vancouver", "short_code" => "BC", "status" => 1 ],
            [ "id" => 575, "state_id" => 5, "name" => "Ace-Carson", "slug" => "ace-carson", "short_code" => "", "status" => 1 ],
            [ "id" => 576, "state_id" => 55, "name" => "WINCHESTER", "slug" => "winchester", "short_code" => "QC", "status" => 1 ],
            [ "id" => 577, "state_id" => 76, "name" => "VICTORIA&NANAIMO", "slug" => "victoriananaimo", "short_code" => "BC", "status" => 1 ],
            [ "id" => 578, "state_id" => 76, "name" => "ABBOTSFORD", "slug" => "abbotsford", "short_code" => "BC", "status" => 1 ],
            [ "id" => 579, "state_id" => 76, "name" => "QUEENSBOROUGH", "slug" => "queensborough", "short_code" => "BC", "status" => 1 ],
            [ "id" => 580, "state_id" => 76, "name" => "OSOYOOS", "slug" => "osoyoos", "short_code" => "BC", "status" => 1 ],
            [ "id" => 581, "state_id" => 76, "name" => "PENTICTION", "slug" => "pentiction", "short_code" => "BC", "status" => 1 ],
            [ "id" => 582, "state_id" => 76, "name" => "KELOWNA", "slug" => "kelowna", "short_code" => "BC", "status" => 1 ],
            [ "id" => 583, "state_id" => 76, "name" => "VERNON", "slug" => "vernon", "short_code" => "BC", "status" => 1 ],
            [ "id" => 584, "state_id" => 76, "name" => "KAMLOOPS", "slug" => "kamloops", "short_code" => "BC", "status" => 1 ],
            [ "id" => 585, "state_id" => 76, "name" => "PRINCE GEORGE", "slug" => "prince-george", "short_code" => "BC", "status" => 1 ],
            [ "id" => 586, "state_id" => 76, "name" => "100 MILE HOUSE", "slug" => "100-mile-house", "short_code" => "BC", "status" => 1 ],
            [ "id" => 587, "state_id" => 76, "name" => "KRAMBROOKE", "slug" => "krambrooke", "short_code" => "BC", "status" => 1 ],
            [ "id" => 588, "state_id" => 76, "name" => "FORT ST.JOHN", "slug" => "fort-stjohn", "short_code" => "BC", "status" => 1 ],
            [ "id" => 589, "state_id" => 55, "name" => "QUEBEC CITY", "slug" => "quebec-city", "short_code" => "", "status" => 1 ],
            [ "id" => 590, "state_id" => 29, "name" => "OMAHA", "slug" => "omaha-2", "short_code" => "", "status" => 1 ],
            [ "id" => 591, "state_id" => 56, "name" => "S.T. JOHNS", "slug" => "st-johns", "short_code" => "", "status" => 1 ],
            [ "id" => 592, "state_id" => 57, "name" => "EDMONTON COPART", "slug" => "edmonton-copart", "short_code" => "", "status" => 1 ],
            [ "id" => 593, "state_id" => 46, "name" => "Burlington", "slug" => "burlington", "short_code" => "VT", "status" => 1 ],
        ] );
    }
}
