<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run ()
    {
        DB::table( 'countries' )->insert( [
            [ 'name' => 'Afghanistan', 'slug' => 'afghanistan', 'short_code' => 'AF', 'status' => 1, ],
            [ 'name' => 'Albania', 'slug' => 'lbania', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Algeria', 'slug' => 'lgeria', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'American Samoa', 'slug' => 'merican-samoa', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Andorra', 'slug' => 'ndorra', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Angola', 'slug' => 'ngola', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Antarctica', 'slug' => 'ntarctica', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Antigua And Barbuda', 'slug' => 'ntigua-and-barbuda', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Argentina', 'slug' => 'rgentina', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Armenia', 'slug' => 'rmenia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Aruba', 'slug' => 'ruba', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Australia', 'slug' => 'ustralia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Austria', 'slug' => 'ustria', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Azerbaijan', 'slug' => 'zerbaijan', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Bahamas The', 'slug' => 'ahamas-the', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Bahrain', 'slug' => 'ahrain', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Bangladesh', 'slug' => 'angladesh', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Barbados', 'slug' => 'arbados', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Belarus', 'slug' => 'elarus', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Belgium', 'slug' => 'elgium', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Belize', 'slug' => 'elize', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Benin', 'slug' => 'enin', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Bermuda', 'slug' => 'ermuda', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Bhutan', 'slug' => 'hutan', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Bolivia', 'slug' => 'olivia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Bosnia and Herzegovina', 'slug' => 'osnia-and-herzegovina', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Botswana', 'slug' => 'otswana', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Bouvet Island', 'slug' => 'ouvet-island', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Brazil', 'slug' => 'razil', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'British Indian Ocean Territory', 'slug' => 'ritish-indian-ocean-territory', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Brunei', 'slug' => 'runei', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Bulgaria', 'slug' => 'ulgaria', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Burkina Faso', 'slug' => 'urkina-faso', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Burundi', 'slug' => 'urundi', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Cambodia', 'slug' => 'ambodia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Cameroon', 'slug' => 'ameroon', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Canada', 'slug' => 'anada', 'short_code' => 'ca', 'status' => 1, ],
            [ 'name' => 'Cape Verde', 'slug' => 'cape-verde', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Cayman Islands', 'slug' => 'cayman-islands', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Central African Republic', 'slug' => 'central-african-republic', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Chad', 'slug' => 'chad', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Chile', 'slug' => 'chile', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'China', 'slug' => 'china', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Christmas Island', 'slug' => 'christmas-island', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Cocos (Keeling) Islands', 'slug' => 'cocos-keeling-islands', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Colombia', 'slug' => 'colombia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Comoros', 'slug' => 'comoros', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Congo', 'slug' => 'congo', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Congo The Democratic Republic Of The', 'slug' => 'congo-the-democratic-republic-of-the', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Cook Islands', 'slug' => 'cook-islands', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Costa Rica', 'slug' => 'costa-rica', 'short_code' => null, 'status' => 0, ],
            [ 'name' => "Cote D'Ivoire (Ivory Coast)", 'slug' => 'cote-d-ivoire-ivory-coast', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Croatia (Hrvatska)', 'slug' => 'croatia-hrvatska', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Cuba', 'slug' => 'cuba', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Cyprus', 'slug' => 'cyprus', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Czech Republic', 'slug' => 'czech-republic', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Denmark', 'slug' => 'denmark', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Djibouti', 'slug' => 'djibouti', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Dominica', 'slug' => 'dominica', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Dominican Republic', 'slug' => 'dominican-republic', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'East Timor', 'slug' => 'east-timor', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Ecuador', 'slug' => 'ecuador', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Egypt', 'slug' => 'egypt', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'El Salvador', 'slug' => 'el-salvador', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Equatorial Guinea', 'slug' => 'equatorial-guinea', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Eritrea', 'slug' => 'eritrea', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Estonia', 'slug' => 'estonia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Ethiopia', 'slug' => 'ethiopia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'External Territories of Australia', 'slug' => 'external-territories-of-australia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Falkland Islands', 'slug' => 'falkland-islands', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Faroe Islands', 'slug' => 'faroe-islands', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Fiji Islands', 'slug' => 'fiji-islands', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Finland', 'slug' => 'finland', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'France', 'slug' => 'france', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'French Guiana', 'slug' => 'french-guiana', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'French Polynesia', 'slug' => 'french-polynesia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'French Southern Territories', 'slug' => 'french-southern-territories', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Gabon', 'slug' => 'gabon', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Gambia The', 'slug' => 'gambia-the', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Georgia', 'slug' => 'georgia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Germany', 'slug' => 'germany', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Ghana', 'slug' => 'ghana', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Gibraltar', 'slug' => 'gibraltar', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Greece', 'slug' => 'greece', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Greenland', 'slug' => 'greenland', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Grenada', 'slug' => 'grenada', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Guadeloupe', 'slug' => 'guadeloupe', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Guam', 'slug' => 'guam', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Guatemala', 'slug' => 'guatemala', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Guernsey and Alderney', 'slug' => 'guernsey-and-alderney', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Guinea', 'slug' => 'guinea', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Guinea-Bissau', 'slug' => 'guinea-bissau', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Guyana', 'slug' => 'guyana', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Haiti', 'slug' => 'haiti', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Heard and McDonald Islands', 'slug' => 'heard-and-mcdonald-islands', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Honduras', 'slug' => 'honduras', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Hong Kong S.A.R.', 'slug' => 'hong-kong-s-a-r', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Hungary', 'slug' => 'hungary', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Iceland', 'slug' => 'iceland', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'India', 'slug' => 'india', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Indonesia', 'slug' => 'indonesia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Iran', 'slug' => 'iran', 'short_code' => 'IR', 1 ],
            [ 'name' => 'Iraq', 'slug' => 'iraq', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Ireland', 'slug' => 'ireland', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Israel', 'slug' => 'israel', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Italy', 'slug' => 'italy', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Jamaica', 'slug' => 'jamaica', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Japan', 'slug' => 'japan', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Jersey', 'slug' => 'jersey', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Jordan', 'slug' => 'jordan', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Kazakhstan', 'slug' => 'kazakhstan', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Kenya', 'slug' => 'kenya', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Kiribati', 'slug' => 'kiribati', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Korea North', 'slug' => 'korea-north', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Korea South', 'slug' => 'korea-south', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Kuwait', 'slug' => 'kuwait', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Kyrgyzstan', 'slug' => 'kyrgyzstan', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Laos', 'slug' => 'laos', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Latvia', 'slug' => 'latvia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Lebanon', 'slug' => 'lebanon', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Lesotho', 'slug' => 'lesotho', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Liberia', 'slug' => 'liberia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Libya', 'slug' => 'libya', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Liechtenstein', 'slug' => 'liechtenstein', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Lithuania', 'slug' => 'lithuania', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Luxembourg', 'slug' => 'luxembourg', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Macau S.A.R.', 'slug' => 'macau-s-a-r', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Macedonia', 'slug' => 'macedonia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Madagascar', 'slug' => 'madagascar', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Malawi', 'slug' => 'malawi', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Malaysia', 'slug' => 'malaysia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Maldives', 'slug' => 'maldives', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Mali', 'slug' => 'mali', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Malta', 'slug' => 'malta', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Man (Isle of)', 'slug' => 'man-isle-of', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Marshall Islands', 'slug' => 'marshall-islands', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Martinique', 'slug' => 'martinique', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Mauritania', 'slug' => 'mauritania', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Mauritius', 'slug' => 'mauritius', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Mayotte', 'slug' => 'mayotte', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Mexico', 'slug' => 'mexico', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Micronesia', 'slug' => 'micronesia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Moldova', 'slug' => 'moldova', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Monaco', 'slug' => 'monaco', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Mongolia', 'slug' => 'mongolia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Montserrat', 'slug' => 'montserrat', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Morocco', 'slug' => 'morocco', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Mozambique', 'slug' => 'mozambique', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Myanmar', 'slug' => 'myanmar', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Namibia', 'slug' => 'namibia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Nauru', 'slug' => 'nauru', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Nepal', 'slug' => 'nepal', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Netherlands Antilles', 'slug' => 'netherlands-antilles', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Netherlands The', 'slug' => 'netherlands-the', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'New Caledonia', 'slug' => 'new-caledonia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'New Zealand', 'slug' => 'new-zealand', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Nicaragua', 'slug' => 'nicaragua', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Niger', 'slug' => 'niger', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Nigeria', 'slug' => 'nigeria', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Niue', 'slug' => 'niue', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Norfolk Island', 'slug' => 'norfolk-island', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Northern Mariana Islands', 'slug' => 'northern-mariana-islands', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Norway', 'slug' => 'norway', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Oman', 'slug' => 'oman', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Pakistan', 'slug' => 'pakistan', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Palau', 'slug' => 'palau', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Palestinian Territory Occupied', 'slug' => 'palestinian-territory-occupied', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Panama', 'slug' => 'panama', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Papua new Guinea', 'slug' => 'papua-new-guinea', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Paraguay', 'slug' => 'paraguay', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Peru', 'slug' => 'peru', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Philippines', 'slug' => 'philippines', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Pitcairn Island', 'slug' => 'pitcairn-island', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Poland', 'slug' => 'poland', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Portugal', 'slug' => 'portugal', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Puerto Rico', 'slug' => 'puerto-rico', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Qatar', 'slug' => 'qatar', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Reunion', 'slug' => 'reunion', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Romania', 'slug' => 'romania', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Russia', 'slug' => 'russia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Rwanda', 'slug' => 'rwanda', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Saint Helena', 'slug' => 'saint-helena', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Saint Kitts And Nevis', 'slug' => 'saint-kitts-and-nevis', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Saint Lucia', 'slug' => 'saint-lucia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Saint Pierre and Miquelon', 'slug' => 'saint-pierre-and-miquelon', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Saint Vincent And The Grenadines', 'slug' => 'saint-vincent-and-the-grenadines', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Samoa', 'slug' => 'samoa', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'San Marino', 'slug' => 'san-marino', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Sao Tome and Principe', 'slug' => 'sao-tome-and-principe', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Saudi Arabia', 'slug' => 'saudi-arabia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Senegal', 'slug' => 'senegal', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Serbia', 'slug' => 'serbia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Seychelles', 'slug' => 'seychelles', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Sierra Leone', 'slug' => 'sierra-leone', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Singapore', 'slug' => 'singapore', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Slovakia', 'slug' => 'slovakia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Slovenia', 'slug' => 'slovenia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Smaller Territories of the UK', 'slug' => 'smaller-territories-of-the-uk', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Solomon Islands', 'slug' => 'solomon-islands', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Somalia', 'slug' => 'somalia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'South Africa', 'slug' => 'south-africa', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'South Georgia', 'slug' => 'south-georgia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'South Sudan', 'slug' => 'south-sudan', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Spain', 'slug' => 'spain', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Sri Lanka', 'slug' => 'sri-lanka', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Sudan', 'slug' => 'sudan', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Suriname', 'slug' => 'suriname', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Svalbard And Jan Mayen Islands', 'slug' => 'svalbard-and-jan-mayen-islands', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Swaziland', 'slug' => 'swaziland', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Sweden', 'slug' => 'sweden', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Switzerland', 'slug' => 'switzerland', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Syria', 'slug' => 'syria', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Taiwan', 'slug' => 'taiwan', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Tajikistan', 'slug' => 'tajikistan', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Tanzania', 'slug' => 'tanzania', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Thailand', 'slug' => 'thailand', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Togo', 'slug' => 'togo', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Tokelau', 'slug' => 'tokelau', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Tonga', 'slug' => 'tonga', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Trinidad And Tobago', 'slug' => 'trinidad-and-tobago', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Tunisia', 'slug' => 'tunisia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Turkey', 'slug' => 'turkey', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Turkmenistan', 'slug' => 'turkmenistan', 'short_code' => 'TR', 1, ],
            [ 'name' => 'Turks And Caicos Islands', 'slug' => 'turks-and-caicos-islands', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Tuvalu', 'slug' => 'tuvalu', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Uganda', 'slug' => 'uganda', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Ukraine', 'slug' => 'ukraine', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'United Arab Emirates', 'slug' => 'united-arab-emirates', 'short_code' => 'UAE', 'status' => 1, ],
            [ 'name' => 'United Kingdom', 'slug' => 'united-kingdom', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'United States', 'slug' => 'united-states', 'short_code' => 'USA', 'status' => 1, ],
            [ 'name' => 'United States Minor Outlying Islands', 'slug' => 'united-states-minor-outlying-islands', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Uruguay', 'slug' => 'uruguay', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Uzbekistan', 'slug' => 'uzbekistan', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Vanuatu', 'slug' => 'vanuatu', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Vatican City State (Holy See)', 'slug' => 'vatican-city-state-holy-see', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Venezuela', 'slug' => 'venezuela', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Vietnam', 'slug' => 'vietnam', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Virgin Islands (British)', 'slug' => 'virgin-islands-british', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Virgin Islands (US)', 'slug' => 'virgin-islands-us', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Wallis And Futuna Islands', 'slug' => 'wallis-and-futuna-islands', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Western Sahara', 'slug' => 'western-sahara', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Yemen', 'slug' => 'yemen', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Yugoslavia', 'slug' => 'yugoslavia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Zambia', 'slug' => 'zambia', 'short_code' => null, 'status' => 0, ],
            [ 'name' => 'Zimbabwe', 'slug' => 'zimbabwe', 'short_code' => null, 'status' => 0, ],
        ] );
    }
}
