<?php

namespace Database\Seeders;

use App\Enums\Roles;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run ()
    {
        DB::table( 'users' )->insert( [
            [
                'id'        => 100001,
                "username"  => 'admin',
                "email"     => 'admin@aslshippingline.com',
                "password"  => Hash::make( 'Admin@07@$!#' ),
                "role"      => 0,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100002,
                "username"  => 'Robin',
                "email"     => 'operation@aslshippingline.com',
                "password"  => Hash::make( 'Robin@ASL$!123' ),
                "role"      => 1,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100003,
                "username"  => 'Ivy',
                "email"     => 'ivy@arianaworldwide.com',
                "password"  => Hash::make( 'Ivy@123*' ),
                "role"      => 1,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100004,
                "username"  => 'asl_altaf',
                "email"     => 't@aslshippingline.com',
                "password"  => Hash::make( 'A@sL$taf' ),
                "role"      => 6,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100005,
                "username"  => 'dxb_bal',
                "email"     => 'uzman@aslshippingline.com',
                "password"  => Hash::make( '9006123$' ),
                "role"      => 2,
                "locations" => '[5]',
                "status"    => 1,
            ],
            [
                'id'        => 100006,
                "username"  => 'Bal_shabir',
                "email"     => 'bl@aslshippingline1.com',
                "password"  => Hash::make( 'sh@b!17r' ),
                "role"      => 2,
                "locations" => '[5]',
                "status"    => 1,
            ],
            [
                'id'        => 100007,
                "username"  => 'dev@impulsion',
                "email"     => 'izhar470@gmail.com',
                "password"  => Hash::make( 'dev@2022' ),
                "role"      => Roles::MASTER_ADMIN,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100008,
                "username"  => 'Homayon',
                "email"     => 'homayoon@arianaworldwide.com',
                "password"  => Hash::make( 'Farhan' ),
                "role"      => 1,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100009,
                "username"  => 'Shah_jahan',
                "email"     => 'shahjahan@gmail.com',
                "password"  => Hash::make( 'Shah@1122' ),
                "role"      => 1,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100010,
                "username"  => 'mahdi',
                "email"     => 'njoffice@aslshipping.com',
                "password"  => Hash::make( 'mahdi2020' ),
                "role"      => 2,
                "locations" => '[5]',
                "status"    => 1,
            ],
            [
                'id'        => 100011,
                "username"  => 'ajmal',
                "email"     => 'ariana.clearing1@gmail.com',
                "password"  => Hash::make( 'Ajm@L' ),
                "role"      => 6,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100012,
                "username"  => 'clearance_ann',
                "email"     => 'clearance_ann@gamil.com',
                "password"  => Hash::make( 'clearance01' ),
                "role"      => 6,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100013,
                "username"  => 'clearance_jessica',
                "email"     => 'clearance_tx@gmail.com',
                "password"  => Hash::make( 'clearance02' ),
                "role"      => 1,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100014,
                "username"  => 'Bakhtawar_asl',
                "email"     => '24seven@aslshippingline.com',
                "password"  => Hash::make( 'Lucky@007' ),
                "role"      => 0,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100015,
                "username"  => "accounts.amin",
                "email"     => "accounts@aslshipping.com",
                "password"  => Hash::make("Amin@ccA@$!"),
                "role"      => 5,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100016,
                "username"  => 'faishal',
                "email"     => 'Inquiry@arianaworldwide.com',
                "password"  => Hash::make( 'faishal2020' ),
                "role"      => 1,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100017,
                "username"  => 'afraz',
                "email"     => 'afraz@gmail.com',
                "password"  => Hash::make( 'abuhamza' ),
                "role"      => 4,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100018,
                "username"  => 'GA_ACC',
                "email"     => 'accounts.ga@gmail.com',
                "password"  => Hash::make( 'Zolkaikhan#2798' ),
                "role"      => 2,
                "locations" => '[2]',
                "status"    => 1,
            ],
            [
                'id'       => 100019,
                "username" => 'asl.mishal',
                "emails" => 'asl.mishal@gmail.com',
                "password"  => Hash::make( 'm!$7@L07#'),
                "role"      => 1,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100020,
                "username"  => 'la_office',
                "email"     => 'la_office@gmail.com',
                "password"  => Hash::make( 'la@usa' ),
                "role"      => 2,
                "locations" => '[1]',
                "status"    => 1,
            ],
            [
                'id'        => 100021,
                "username"  => 'ga_office',
                "email"     => 'ga_office@gmail.com',
                "password"  => Hash::make( 'ga@usa' ),
                "role"      => 2,
                "locations" => '[2]',
                "status"    => 1,
            ],
            [
                'id'        => 100022,
                "username"  => 'shabir',
                "email"     => 'shabir_usa@gmail.com',
                "password"  => Hash::make( 'us@shabir' ),
                "role"      => 6,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100023,
                "username"  => 'newjersey_office',
                "email"     => 'newjersey_office@gmail.com',
                "password"  => Hash::make( 'newjersey_office' ),
                "role"      => 2,
                "locations" => '[8]',
                "status"    => 1,
            ],
            [
                'id'        => 100024,
                "username"  => 'txacc_nej',
                "email"     => 'txacc_nej@gmail.com',
                "password"  => Hash::make( 'Zolkaikhan#2798' ),
                "role"      => 2,
                "locations" => '[7]',
                "status"    => 1,
            ],
            [
                'id'        => 100025,
                "username"  => 'NJN_acc',
                "email"     => 'njacc_nej@gmail.com',
                "password"  => Hash::make( '9006123$' ),
                "role"      => 2,
                "locations" => '[8]',
                "status"    => 1,
            ],
            [
                'id'        => 100026,
                "username"  => 'shabir_texas',
                "email"     => 'shabir_texas@gmail.com',
                "password"  => Hash::make( 'shbr@texas' ),
                "role"      => 2,
                "locations" => '[7]',
                "status"    => 1,
            ],
            [
                'id'        => 100027,
                "username"  => 'shabir_newjersey',
                "email"     => 'shabir_newjersey@gmail.com',
                "password"  => Hash::make( 'shbr@newjersey' ),
                "role"      => 2,
                "locations" => '[8]',
                "status"    => 1,
            ],
            [
                'id'        => 100028,
                "username"  => 'ga',
                "email"     => 'ga@gmail.com',
                "password"  => Hash::make( 'admin_GA' ),
                "role"      => 2,
                "locations" => '[2]',
                "status"    => 1,
            ],
            [
                'id'        => 100029,
                "username"  => 'bal_faramarz',
                "email"     => 'bal_faramarz@gmail.com',
                "password"  => Hash::make( 'f@7am@3!*' ),
                "role"      => 2,
                "locations" => '[5]',
                "status"    => 1,
            ],
            [
                'id'        => 100030,
                "username"  => 'Clearance_Jamil',
                "email"     => 'amayacars934@GMAIL.COM',
                "password"  => Hash::make( 'clearance02' ),
                "role"      => 1,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100031,
                "username"  => 'Altaf_Sh',
                "email"     => 'Altaf@aslshippingline.com',
                "password"  => Hash::make( 'A!t@f*07' ),
                "role"      => 6,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100032,
                "username"  => 'Yasir_sh',
                "email"     => 'yasir@aslshippingline.com',
                "password"  => Hash::make( 'Y@$!r*10' ),
                "role"      => 6,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100033,
                "username"  => 'Haroon_sh',
                "email"     => 'haroon@aslshippingline.com',
                "password"  => Hash::make( 'H@r*123' ),
                "role"      => 6,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100034,
                "username"  => 'Sarfarazasl',
                "email"     => 'sarfaraz@aslshippinline.com',
                "password"  => Hash::make( '9006123$' ),
                "role"      => 6,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100035,
                "username"  => 'Izhar',
                "email"     => 'izhar@gmail.com',
                "password"  => Hash::make( 'Izh@r' ),
                "role"      => 1,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100036,
                "username"  => 'TXN_Office',
                "email"     => 'TXN@aslshippingline.com',
                "password"  => Hash::make( 'Tx@N07' ),
                "role"      => 2,
                "locations" => '[7]',
                "status"    => 1,
            ],
            [
                'id'        => 100037,
                "username"  => 'AMEER',
                "email"     => 'AMEER@ASLSHIPPINGLINE.com',
                "password"  => Hash::make( 'AmEErA$!' ),
                "role"      => 6,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100038,
                "username"  => 'BALTIMORE_MARITIME',
                "email"     => 'Bal_maritime@aslshippingline.com',
                "password"  => Hash::make( 'Maritime@007' ),
                "role"      => 7,
                "locations" => '[5]',
                "status"    => 1,
            ],
            [
                'id'        => 100039,
                "username"  => 'MIRSHARQ',
                "email"     => 'mirsharq@yahoo.com',
                "password"  => Hash::make( 'Mir@ASL' ),
                "role"      => 4,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100040,
                "username"  => 'zafar',
                "email"     => 'ZAFER@aslshippingline.com',
                "password"  => Hash::make( 'zafar@636872' ),
                "role"      => 4,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100041,
                "username"  => 'viewlocation',
                "email"     => 'viewlocation@gmail.com',
                "password"  => Hash::make( 'Haris@2022' ),
                "role"      => Roles::LOCATION_VIEW_ADMIN,
                "locations" => '[]',
                "status"    => 1,
            ],
            [
                'id'        => 100042,
                "username"  => 'rizwan',
                "email"     => 'rizwan@aslshippingline.com',
                "password"  => Hash::make( 'Rizwan2021' ),
                "role"      => 4,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100043,
                "username"  => 'Haris',
                "email"     => 'haris@arianawwm.com',
                "password"  => Hash::make( 'Haris@2022' ),
                "role"      => 4,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100044,
                "username"  => 'GA_Team',
                "email"     => 'gateam@aslahippingline.com',
                "password"  => Hash::make( 'GA*Team' ),
                "role"      => 2,
                "locations" => '[2]',
                "status"    => 1,
            ],
            [
                'id'        => 100045,
                "username"  => 'OFFLOADING_YARD',
                "email"     => 'Yard@aslshippingline.com',
                "password"  => Hash::make( 'Yard2021' ),
                "role"      => 4,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100046,
                "username"  => 'GA_APP',
                "email"     => 'ga.app@aslshippingline.com',
                "password"  => Hash::make( 'Ga_App' ),
                "role"      => 2,
                "locations" => '[2]',
                "status"    => 1,
            ],
            [
                'id'        => 100047,
                "username"  => 'GA_NEW',
                "email"     => 'GA_new@aslshippingline.com',
                "password"  => Hash::make( 'Ga_new' ),
                "role"      => 2,
                "locations" => '[2]',
                "status"    => 1,
            ],
            [
                'id'        => 100048,
                "username"  => 'Rizwan_Sale',
                "email"     => 'Rizwan.Sale@aslShippingline.com',
                "password"  => Hash::make( 'Rizwan@1207' ),
                "role"      => 4,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100049,
                "username"  => 'GA_2021',
                "email"     => 'Ga2021@aslshipping.com',
                "password"  => Hash::make( 'Ga@2021' ),
                "role"      => 2,
                "locations" => '[2]',
                "status"    => 1,
            ],
            [
                'id'        => 100050,
                "username"  => 'Rizwan_Shj',
                "email"     => 'Rizwan.shj@aslshippingline.com',
                "password"  => Hash::make( 'Rizwan07#' ),
                "role"      => 6,
                "locations" => null,
                "status"    => 1,
            ],
            [
                'id'        => 100051,
                "username"  => 'Texas2',
                "email"     => 'tx.operation@aslshippingline.com',
                "password"  => Hash::make( 'texas2@asl' ),
                "role"      => 2,
                "locations" => '[10]',
                "status"    => 1,
            ],
            [
                'id'        => 100052,
                "username"  => 'shabir_tx2',
                "email"     => 'shabirtx2@aslshipping.com',
                "password"  => Hash::make( 'Sh@bir@tx2' ),
                "role"      => 2,
                "locations" => '[10]',
                "status"    => 1,
            ],
            [
                'id'        => 100053,
                "username"  => 'NJ2_Faramarz',
                "email"     => 'NewNJ2@aslshippingline.com',
                "password"  => Hash::make( 'Asl@2022' ),
                "role"      => 2,
                "locations" => '[11]',
                "status"    => 1,
            ],
            [
                'id'        => 100054,
                "username"  => 'SarfrazNJ_VS',
                "email"     => 'SarfrazNJ.vs@gmail.com',
                "password"  => Hash::make( '9006123$' ),
                "role"      => 2,
                "locations" => '[11]',
                "status"    => 1,
            ],
            [
                'id'        => 100055,
                "username"  => 'Ga_2022',
                "email"     => 'GA2022@aslshippingline.com',
                "password"  => Hash::make( 'Ga@2022' ),
                "role"      => 2,
                "locations" => '[2]',
                "status"    => 1,
            ],
        ] );
    }
}
