<style type="text/css">
    body {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }

    .km-heading {
        background-color: #D9FBFA;
        font-size: 13px;
        font-weight: bolder;
        /*text-align: center;*/
    }

    .km-heading1 {
        background-color: #D9FBFA;

    }

    table {
        font-size: 12px;

    }

    header {
        position: fixed;
        top: -40px;
    }

    footer {
        position: fixed;
        bottom: -30px;
    }

    td {
        text-align: justify;
    }

    .km-border {
        border-bottom: none;
        border-right: none;
        border-top: none;
        border-left: none;
        border-spacing: 0 4px;

    }

    .pagenum:before {
        content: counter(page);
    }

    input {
        transform: translateY(7px);
    }
</style>
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<header style="width:100%;">
    <table width="100%">
        <tr>
            <td>
                Generated By: {{ env('APP_NAME') }}
            </td>
            <td></td>
            <td style="text-align: right;">Generated On: Sat, 22 May 2021 17:27:55 +0000
            </td>
        </tr>
    </table>
    <hr style="margin-top: -2px;">
</header>

<footer style="width: 100%;">
    <p style="text-align: center; border-top: 2px solid #282C35;"><span class="pagenum"></span></p>
</footer>

<div>
    <table width="100%" cellspacing="0" cellpadding="6">
        <tr>
{{--            <td width="33.33%"><img src="{{ url('images/logo.jpg') }}" width="70px" height="50px"></td>--}}
            <td width="33.33%"><img src="https://backend.aslshippingline.com/images/logo.jpg" width="70px" height="50px"></td>

            <td style="font-size: 15px; text-align: center;"> &nbsp;&nbsp;&nbsp;131 East Gardena <br>Boulevard Gardena, CA 90248 <br>&nbsp;&nbsp;&nbsp;Tel:
                (310) 532-8557
            </td>
            <td style="font-weight: bolder;color: black; font-size: 15px; text-align: center;">Vehicle Condition
                Report
            </td>
        </tr>
    </table>
    <table width="100%">
        <tr>
            <td width="50%">
                <table width="100%" cellspacing="0" cellpadding="1" style="border-collapse: separate;" border="1px" class="km-border">
                    <tr>
                        <td class="km-heading">Customer</td>
                        <td colspan="3">{{ data_get( $vehicle, 'customer.customer_name' ) }}</td>
                    </tr>
                    <tr>
                        <td class="km-heading"
                            style="background-color: #d9fbfa;border: 1px solid #000; padding: 0px; height: 39px;">
                            Address
                        </td>
                        <td colspan="3"
                            style="border: 1px solid #000; padding: 0px; height: 18px; height: 39px;">{{ data_get( $vehicle, 'location.name' ) }}</td>
                    </tr>
                    <tr>
                        <td class="km-heading" width="10%">Phone #</td>
                        <td width="40%">{{ data_get( $vehicle, 'customer.phone' ) }}</td>
                        <td class="km-heading">Weight</td>
                        <td>{{ $vehicle->weight }}</td>
                    </tr>
                    <tr>
                        <td class="km-heading">Lot #</td>
                        <td>{{ $vehicle->lot_number }}</td>
                        <td class="km-heading">Inv #</td>
                        <td>{{ $vehicle->hat_number }}</td>
                    </tr>
                    <tr>
                        <td class="km-heading" style="padding:10px;">Destination</td>
                        <td colspan="3"></td>
                    </tr>
                    <tr>
                        <td class="km-heading">Condition</td>
                        <td>{{ data_get( $vehicle, 'towing_request.condition') == '1' ? 'Operable' : 'Non Operable' }}</td>
                        <td class="km-heading">Damaged</td>
                        <td>{{ data_get( $vehicle, 'towing_request.damaged') == '1' ? 'Yes' : 'No' }}</td>
                    </tr>

                </table>
            </td>
            <td width="50%">
                <table width="100%" cellspacing="0" cellpadding="1" style="border-collapse: separate;"
                       border="1px" class="km-border">
                    <tr>
                        <td class="km-heading">Year</td>
                        <td>{{ $vehicle->year }}</td>
                        <td class="km-heading">Color</td>
                        <td>{{ $vehicle->color }}</td>
                        <td class="km-heading">VCR#</td>
                        <td>{{ $vehicle->vcr }}</td>
                    </tr>
                    <tr>
                        <td class="km-heading">Model</td>
                        <td colspan="2">{{ $vehicle->model }}</td>
                        <td class="km-heading">Make</td>
                        <td colspan="2">{{ $vehicle->make }}</td>
                    </tr>
                    <tr>
                        <td class="km-heading">VIN</td>
                        <td colspan="5">{{ $vehicle->vin }}</td>
                    </tr>
                    <tr>
                        <td class="km-heading">License#</td>
                        <td colspan="5">{{ $vehicle->license_number }}</td>
                    </tr>
                    <tr>
                        <td class="km-heading" colspan="2">Towed From</td>
                        <td colspan="4">{{ $vehicle->towed_from }}</td>
                    </tr>
                    <tr>
                        <td class="km-heading" colspan="2" style="font-size:13px;">Towed Amount</td>
                        <td colspan="1">{{ $vehicle->towed_amount }}</td>
                        <td class="km-heading" colspan="2" style="font-size:13px;">Storage Amount</td>
                        <td colspan="1">{{ $vehicle->storage_amount }}</td>
                    </tr>
                    <tr>
                        <td class="km-heading" style="font-size:13px;">Towed</td>
                        <td>{{ data_get($vehicle, 'towing_request.towed' ) == '1' ? 'Yes' : 'No' }}</td>
                        <td class="km-heading" style="font-size:13px;">Title Provided</td>
                        <td>{{ data_get($vehicle, 'towing_request.title_received' ) == '1' ? 'Yes' : 'No' }}</td>
                        <td class="km-heading" style="font-size:13px;">Pictures</td>
                        <td>{{ data_get($vehicle, 'towing_request.pictures' ) == '1' ? 'Yes' : 'No' }}</td>
                    </tr>

                </table>
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <table width="100%" cellspacing="0" cellpadding="1" style="border-collapse: separate; margin-top: -5px;" border="1px" class="km-border">
                    <tr>
                        <td colspan="5" style="text-align: center;">
                            <b>CHECK OPTIONS INCLUDED IN VEHICLE</b>
                        </td>
                    </tr>
                    <tr>
                        <td><input type="checkbox" @if(in_array(1, $vehicleFeatureIds) || $vehicle->keys == '1') checked @endif>Keys</td>
                        <td><input type="checkbox" @if(in_array(3, $vehicleFeatureIds)) checked @endif>CD Changer</td>
                        <td><input type="checkbox" @if(in_array(4, $vehicleFeatureIds)) checked @endif>GPS Navigation System</td>
                        <td><input type="checkbox" @if(in_array(5, $vehicleFeatureIds)) checked @endif>Spare Tire/Jack</td>
                        <td><input type="checkbox" @if(in_array(6, $vehicleFeatureIds)) checked @endif>Wheel Covers</td>
                    </tr>
                    <tr>
                        <td><input type="checkbox" @if(in_array(7, $vehicleFeatureIds)) checked @endif> Radio</td>
                        <td><input type="checkbox" @if(in_array(8, $vehicleFeatureIds)) checked @endif> CD Player</td>
                        <td><input type="checkbox" @if(in_array(10, $vehicleFeatureIds)) checked @endif> Mirror</td>
                        <td><input type="checkbox" @if(in_array(11, $vehicleFeatureIds)) checked @endif> Speaker</td>
                        <td><input type="checkbox" @if(in_array(12, $vehicleFeatureIds)) checked @endif> Other</td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <table width="100%" cellspacing="0" cellpadding="1" style="border-collapse: separate;margin-top: -5px;" border="1px" class="km-border">
                    <tr>
                        <td style="text-align:center;" colspan="8"><b>CONDITION OF VEHICLE</b></td>
                    </tr>
                    <tr>
                        <td style="text-align:center;" colspan="8"><b>Indicate any damage to the vehicle using the following legend.</b></td>
                    </tr>
                    <tr>
                        <td class="km-heading1" style="font-size:13px;">H</td>
                        <td>Hairline Scratch</td>
                        <td class="km-heading1" style="font-size:13px;">PT</td>
                        <td>Pitted</td>
                        <td class="km-heading1" style="font-size:13px;">T</td>
                        <td>Torn</td>
                        <td class="km-heading1" style="font-size:13px;">B</td>
                        <td>Bent</td>
                    </tr>
                    <tr>
                        <td class="km-heading1" style="font-size:13px;">GC</td>
                        <td>Glass Cracked</td>
                        <td class="km-heading1" style="font-size:13px;"> M</td>
                        <td>Missing</td>
                        <td class="km-heading1" style="font-size:13px;">SM</td>
                        <td>Smashed</td>
                        <td class="km-heading1" style="font-size:13px;">R</td>
                        <td>Rusty</td>
                    </tr>
                    <tr>
                        <td class="km-heading1" style="font-size:13px;">CR</td>
                        <td>Creased</td>
                        <td class="km-heading1" style="font-size:13px;">S</td>
                        <td>Scratched</td>
                        <td class="km-heading1" style="font-size:13px;">ST</td>
                        <td>Stained</td>
                        <td class="km-heading1" style="font-size:13px;">BR</td>
                        <td>Broken</td>
                    </tr>

                    <tr>
                        <td class="km-heading1" style="font-size:13px;">D</td>
                        <td>Dented</td>
                    </tr>

                </table>
            </td>
        </tr>
        <tr>
            <td height="120px" width="50%">
                <table width="100%" cellspacing="0" cellpadding="1" style="border-collapse: separate;" border="1px">
                    <tr>
                        <td rowspan="6" style="border: none; text-align: center;">
                            <img src="{{ url('images/Car-Front.jpg') }}" height="110px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table width="100%">
                                <td class="km-heading1">01</td>
                                <td>{{ \Illuminate\Support\Arr::get($vehicleConditions, 2, '') }}</td>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table width="100%">
                                <td class="km-heading1">02</td>
                                <td>{{ \Illuminate\Support\Arr::get($vehicleConditions, 3, '') }}</td>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table width="100%">
                                <td class="km-heading1">03</td>
                                <td>{{ \Illuminate\Support\Arr::get($vehicleConditions, 4, '') }}</td>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table width="100%">
                                <td class="km-heading1">04</td>
                                <td>{{ \Illuminate\Support\Arr::get($vehicleConditions, 5, '') }}</td>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table width="100%">
                                <td class="km-heading1">05</td>
                                <td>{{ \Illuminate\Support\Arr::get($vehicleConditions, 6, '') }}</td>
                            </table>
                        </td>
                    </tr>


                </table>
            </td>
            <td height="120px" width="50%">
                <table width="100%" cellspacing="0" cellpadding="1" style="border-collapse: separate;" border="1px">
                    <tr>
                        <td rowspan="6" style="border: none; text-align: center;">
                            <img src="{{ url('images/Car-Back.jpg') }}" height="110px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table width="100%">
                                <td class="km-heading1">06</td>
                                <td>{{ \Illuminate\Support\Arr::get($vehicleConditions, 7, '') }}</td>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table width="100%">
                                <td class="km-heading1">07</td>
                                <td>{{ \Illuminate\Support\Arr::get($vehicleConditions, 8, '') }}</td>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table width="100%">
                                <td class="km-heading1">08</td>
                                <td>{{ \Illuminate\Support\Arr::get($vehicleConditions, 9, '') }}</td>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table width="100%">
                                <td class="km-heading1">09</td>
                                <td>{{ \Illuminate\Support\Arr::get($vehicleConditions, 10, '') }}</td>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table width="100%">
                                <td class="km-heading1">10</td>
                                <td>{{ \Illuminate\Support\Arr::get($vehicleConditions, 11, '') }}</td>
                            </table>
                        </td>
                    </tr>

                </table>
            </td>
        </tr>

        <tr>
            <td height="140px" width="50%">
                <table width="100%" cellspacing="0" cellpadding="1" style="border-collapse: separate;" border="1px">
                    <tr>
                        <td colspan="3" style="border: none; text-align: center;">
                            <img src="{{ url('images/driver.jpg') }}" height="110px">
                        </td>
                    </tr>
                    <tr>
                        <td><span class="km-heading1">11 </span><span>{{ \Illuminate\Support\Arr::get($vehicleConditions, 12, '') }}</span></td>
                        <td><span class="km-heading1">12 </span><span>{{ \Illuminate\Support\Arr::get($vehicleConditions, 13, '') }}</span></td>
                        <td><span class="km-heading1">13 </span><span>{{ \Illuminate\Support\Arr::get($vehicleConditions, 14, '') }}</span></td>
                    </tr>
                    <tr>
                        <td><span class="km-heading1">14 </span><span>{{ \Illuminate\Support\Arr::get($vehicleConditions, 15, '') }}</span></td>
                        <td><span class="km-heading1">15 </span><span>{{ \Illuminate\Support\Arr::get($vehicleConditions, 16, '') }}</span></td>
                        <td><span class="km-heading1">16 </span><span>{{ \Illuminate\Support\Arr::get($vehicleConditions, 17, '') }}</span></td>
                    </tr>
                </table>
            </td>

            <td height="140px" width="50%">
                <table width="100%" cellspacing="0" cellpadding="1" style="border-collapse: separate;" border="1px">
                    <tr>
                        <td colspan="3" style="border: none; text-align: center;">
                            <img src="{{ url('images/Passenger.jpg') }}" height="110px">
                        </td>
                    </tr>
                    <tr>
                        <td><span class="km-heading1">17 </span> <span>{{ \Illuminate\Support\Arr::get($vehicleConditions, 18, '') }}</span></td>
                        <td><span class="km-heading1">18 </span><span>{{ \Illuminate\Support\Arr::get($vehicleConditions, 20, '') }}</span></td>
                        <td><span class="km-heading1">19 </span><span>{{ \Illuminate\Support\Arr::get($vehicleConditions, 21, '') }}</span></td>
                    </tr>
                    <tr>
                        <td><span class="km-heading1">20 </span><span>{{ \Illuminate\Support\Arr::get($vehicleConditions, 22, '') }}</span></td>
                        <td><span class="km-heading1">21 </span><span>{{ \Illuminate\Support\Arr::get($vehicleConditions, 23, '') }}</span></td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <table border="1px">
                    <tr>
                        <td style="font-size:12px"> 1. Liability-Shipper (customer) must have door-to-door insurance
                            while goods are in warehouse and during transit. {{ env('APP_NAME') }} will not assume any responsibility for uninsured or underinsured shipment(s)..
                            2. Rates for individual cars are based on consolidation; company is not responsible for
                            exact shipping dates. Company is
                            not responsible for delays in shipping schedules and/or transit time or custom charges and
                            delays..
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr>
            <td colspan="2" style="font-size:12px">
                <b>DIMENSIONS</b>: The above is an accurate representation of the condition of the vehicle at the time
                of loading. NOTICE: The
                OWNER'S or AUTHORIZED AGENT'S Signature of the origin is also to the following RELEASE: this will
                authorize CARRIER to
                drive my vehicle either at origin destination between point (s) of loading/unloading and the point(s) of
                pick-up/delivery.
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <table width="100%" cellspacing="0" cellpadding="1" style="border-collapse: separate;">
                    <tr>
                        <td style="font-size:12px;"><b>This above Vehicle has been delivered in the condition described.</b></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <table width="100%" cellspacing="0" cellpadding="1" style="border-collapse: separate;" border="1px">
                    <tr>
                        <td width="20%" class="km-heading">Completed By</td>
                        <td width="50%">{{ data_get( $vehicle, 'customer.customer_name' ) }}</td>
                        <td width="10%" class="km-heading">Date</td>
                        <td width="20%"></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>

<div class="customer_part">
    <table>
        @php $index = 0; $isOpen = false; @endphp
        @foreach ( $vehicle->vehicle_image as $image )
            @if( $index % 2 == 0 && ! $isOpen )
                <tr>
                    @php $isOpen = true; @endphp
                    @endif
                    <td width="50%"><img width="100%" height="300px" src="{{ Storage::url( $image->name ) }}"></td>
                    @php $index++; @endphp
                    @if( $index % 2 == 0 && $isOpen )
                </tr>
                @php $isOpen = false; @endphp
            @endif
        @endforeach
    </table>
</div>
</body>
</html>
