<style type="text/css">
    td {
        font-size: 9px;
        font-family: Helvetica, sans-serif;
    }

    .wrapper {
         margin-top: 20px;
        width: 100%;
    }

    table {
        width: 100% !important;
        font-size: 11px;
    }

    header {
        position: fixed;
        top: -30px;
    }

    footer {
        position: fixed;
        bottom: -30px;
    }

    .pagenum:before {
        content: counter(page);
    }

     .page-break {
         page-break-after: always;
     }
</style>
<!DOCTYPE html>
<html>
<head>
    <title>LANDING PDF| {{ env('APP_NAME') }}</title>
</head>
<body>
<header>
    <table width="100%" style="border-bottom: 1px solid #333; width:100%;">
        <tr>
            <td>
                <small><strong>Generated By: {{ env('APP_NAME') }}</strong></small>
            </td>
            <td></td>
            <td style="text-align: right;"><small><strong>Generated On: {{ date('r') }}</strong></small></td>
        </tr>
    </table>
</header>

<footer style="width: 100%">
    <p style="text-align: center; border-top: 1px solid #333; ">Page <span class="pagenum"></span></p>
</footer>

<div style="margin-bottom: 15px">
    @foreach($data as $index => $item)
        @php $status = ""; @endphp
        <div class="wrapper">
                @foreach(collect($item['vehicles'])->sortBy([['status', 'asc'], ['age', 'desc']]) as $key => $vehicle)

                @if($status != $vehicle['status'])
                    @if($status != "")
                        <tbody>
                        </table>
                        <br>
                        @endif
                    @php $status = $vehicle['status'];  @endphp

                <span><strong>{{ data_get($item, 'heading.company_name') }}</strong></span> <br>
                <span><strong>CUSTOMER : {{ data_get($item, 'heading.inventory') }}</strong> </span> <br>
                <span><strong>CUSTOMER ID: {{ data_get($item, 'heading.customer_id') }} LOCATION : </strong> {{ data_get($item, 'heading.location') }} <strong>STATUS :</strong> {{ $vehicle['status'] }} </span>

                <table class="table" width="100%" border="1" cellspacing="0">
                    <thead>
                        <tr>
                            <th>HAT NO</th>
                            <th>DATE RECEIVED</th>
                            <th>YEAR</th>
                            <th>MAKE</th>
                            <th>MODEL</th>
                            <th>COLOR</th>
                            <th>VIN</th>
                            <th>TITLE</th>
                            <th>TYPE</th>
                            <th>KEYS</th>
                            <th>AGE</th>
                            <th>LOT NO</th>
                            <th>NOTE</th>
                        </tr>
                    </thead>
                    @endif

                    <tr>
                        <td>{{ $vehicle['hat_no'] }}</td>
                        <td>{{ $vehicle['date_received'] }}</td>
                        <td>{{ $vehicle['year'] }}</td>
                        <td>{{ $vehicle['make'] }}</td>
                        <td>{{ $vehicle['model'] }}</td>
                        <td>{{ $vehicle['color'] }}</td>
                        <td>{{ $vehicle['vin'] }}</td>
                        <td>{{ $vehicle['title'] }}</td>
                        <td>{{ $vehicle['title_type'] }}</td>
                        <td>{{ $vehicle['keys'] }}</td>
                        <td>{{ $vehicle['age'] }}</td>
                        <td>{{ $vehicle['lot_number'] }}</td>
                        <td>{{ $vehicle['note'] }}</td>
                    </tr>

                @endforeach
                    <tbody>
                </table>
        </div>
    @if( $index < count($data) -1)
        <div class="page-break"></div>
    @endif
    @endforeach
</div>
</body>
</html>
