<style type="text/css">
    td {
        font-family: Arial, Helvetica, sans-serif;
    }

    .km-heading {
        background-color: #EBF5F5;
        /*font-weight: bold;*/
        font-size: 15px;
    }

    table {
        font-size: 14px;
    }

    header {
        position: fixed;
        top: -30px;
    }

    footer {
        position: fixed;
        bottom: -30px;
    }

    .pagenum:before {
        content: counter(page);
    }
</style>
<!DOCTYPE html>
<html>
<head>
    <title>LANDING PDF| {{ env('APP_NAME') }}</title>
</head>
<body>
<header>
    <table width="100%" style="border-bottom: 1px solid #333;">
        <tr>
            <td>
                <small><strong>Generated By: {{ env('APP_NAME') }}</strong></small>
            </td>
            <td></td>
            <td style="text-align: right;"><small><strong>Generated On: {{ date('r') }}</strong></small></td>
        </tr>
    </table>
</header>

<footer>
    <p style="text-align: center; border-top: 1px solid #333;">Page <span class="pagenum"></span></p>
</footer>

<div>
    <table border="1px" width="100%" cellspacing="0">
        <tr>
            <td class="km-heading" width="45%" style="font-weight: bolder;color: black; font-size: 16px;">
                <strong>{{ !empty($export->broker_name) ? $export->broker_name : 'Ariana Shipping Line LLC MARITIME' }}</strong>
                {{ empty( $model->oti_number) ? 'OTI License #: 034147' : 'OTI License #: '.$model->oti_number }}

            </td>
            <td width="10%"><img src="https://backend.aslshippingline.com/images/logo.jpg" width="" height="40" alt="{{ env('APP_NAME') }} Logo"></td>

            <td class="km-heading" width="45%" style="font-weight: bolder;color: black; font-size: 16px;">
                <strong>BILL OF LADING</strong>
            </td>
        </tr>
    </table>

    <table border="1px" style="margin-top: 5px; width: 100%;" cellspacing="0" cellpadding="3px">
        <tr class="km-heading">
            <td width="40%">SHIPPER / EXPORTER</td>
            <td width="30%">BOOKING #</td>
            <td width="30%">REFERENCE #</td>
        </tr>
        <tr>
            <td rowspan="4" colspan="1" width="40%">
                {{ data_get($export, 'exporter.company_name'). ' '. data_get($export, 'exporter.address_line_1') }}
            </td>
            <td width="30%">{{ $export->booking_number }}</td>
            <td width="30%">{{ $export->ar_number }}</td>
        <tr>
            <td class="km-heading">PLACE OF RECEIPT</td>
            <td class="km-heading">PORT OF LOADING</td>
        </tr>
        <tr>
            <td>{{ trans('exports.port_of_loadings.'.$export->port_of_loading) }}</td>
            <td>{{ trans('exports.port_of_loadings.'.$export->port_of_loading) }}</td>
        </tr>
        <tr>
            <td class="km-heading">PORT OF DISCHARGE:</td>
            <td>{{ trans('exports.port_of_discharges.'.$export->port_of_discharge) }}</td>
        </tr>
    </table>

    <table border="1px" style="margin-top: 5px; width: 100%;" cellspacing="0">
        <tr class="km-heading">
            <td width="40%">CONSIGNEE</td>
            <td width="30%">PIER #</td>
            <td width="30%">VESSEL #</td>
        </tr>
        <tr>
            <td rowspan="4" colspan="1" width="40%">
                {{ data_get($export, 'houstan_custom_cover_letter.consignee_item.consignee_name') }} <br>
                {{ data_get($export, 'houstan_custom_cover_letter.consignee_item.consignee_address_1') }} <br>
                {{ data_get($export, 'houstan_custom_cover_letter.consignee_item.city.name'). ' '. data_get($export, 'houston_custom_cover_letter.consignee.state.name'). ' '. data_get($export, 'houston_custom_cover_letter.consignee.country.name') }}
            </td>
            <td width="30%">{{ $export->terminal }}</td>
            <td width="30%">{{ $export->vessel }}</td>
        <tr>
            <td><br></td>
            <td><br></td>
        </tr>
        <tr>
            <td class="km-heading">LOADING PIER/TERMINAL</td>
            <td class="km-heading">VOYAGE NO.</td>
        </tr>
        <tr>
            <td>{{ $export->terminal }}</td>
            <td>{{ $export->voyage }}</td>
        </tr>
    </table>

    <table border="1px" style="margin-top: 5px; width: 100%;" cellspacing="0">
        <tr class="km-heading">
            <td width="50%">NOTIFY</td>
            <td width="50%" style="font-size: 15px;"> FOR RELEASE OF CARGO PLEASE CONTACT:</td>
        </tr>
        <tr>
            <td rowspan="2" colspan="1">
                @if(!empty($export->houstan_custom_cover_letter->notify_party))
                    {{ data_get($export, 'houstan_custom_cover_letter.notify_party_item.consignee_name') }} <br>
                    {{ data_get($export, 'houstan_custom_cover_letter.notify_party_item.consignee_address_1') }} <br>
                    {{ data_get($export, 'houstan_custom_cover_letter.notify_party_item.city.name'). ' '. data_get($export, 'houston_custom_cover_letter.notify_party.state.name'). ' '. data_get($export, 'houston_custom_cover_letter.notify_party.country.name') }}
                    <br>
                    Tel: {{ data_get($export, 'houstan_custom_cover_letter.notify_party_item.phone') }}
                @endif
            </td>
            <td style="padding: 30px;"></td>
        </tr>
        <tr>
            <td style="padding: 20px;"><b> ETA/</b>{{ $export->eta }}</td>
        </tr>
    </table>

    <table border="1px" width="100%" style="margin-top: 5px; width: 100%;" cellspacing="0" cellpadding="3px;">
        <tr class="km-heading">
            <td colspan="2">CONTAINER #</td>
            <td colspan="2"> CONTAINER TYPE</td>
            <td colspan="2">SEAL #</td>
            <td colspan="2"> SPECIAL INSTRUCTIONS</td>
        </tr>
        <tr>
            <td colspan="2">{{ $export->container_number }}</td>
            <td colspan="2">{{ trans('exports.container_types.'.$export->container_type) }}</td>
            <td colspan="2">{{ $export->seal_number }}</td>
            <td colspan="2">{{ $export->special_instruction }}</td>
        </tr>
    </table>

    <table border="1px" width="100%" style="margin-top: 5px; width: 100%;" cellspacing="0" cellpadding="3px;">
        <tr class="km-heading">
            <td colspan="2">SHIPPERS DESCRIPTIONS OF GOODS</td>
            <td colspan=""> WEIGHT (KG)</td>
            <td colspan=""> WEIGHT (LB)</td>
            <td colspan="2">CUBE</td>
        </tr>
        <tr>
            <td colspan="2"><b>{{ $export->all_vehicles->count() }} UNITS USED VEHICLES</b></td>
            <td colspan=""></td>
            <td colspan=""></td>
            <td colspan="2"><b> 55 M3 </b></td>
        </tr>
    </table>

    <table border="1px" width="100%" style="margin-top: 5px; width: 100%;" cellspacing="0" cellpadding="3px">
        <tr class="km-heading">
            <td>YEAR</td>
            <td>MAKE</td>
            <td>MODEL/COLOR</td>
            <td>VIN</td>
            <td>WEIGHT  (KG)</td>
            <td>WEIGHT (LB)</td>
            <td>CUBE</td>
        </tr>
        @php $vehicleTotalWeights = 0; $vehicleTotalWeightsInKG = 0;  @endphp
        @foreach($export->all_vehicles as $vehicle)
            @php
                $vehicleTotalWeights += (int) $vehicle->weight;
                $vehicleTotalWeightsInKG += (int) $vehicle->weight_in_kg;
            @endphp
        <tr>
            <td>{{ $vehicle->year }}</td>
            <td>{{ $vehicle->make }}</td>
            <td>{{ $vehicle->model }} / {{ $vehicle->color }}</td>
            <td>{{ $vehicle->vin }}</td>
            <td>{{ round( (int) $vehicle->weight_in_kg) }} KG</td>
            <td>{{ round( (int) $vehicle->weight ) }} LB</td>
            <td></td>
        </tr>
        @endforeach
    </table>

    <table border="1px" width="100%" style="margin-top: 5px; font-size: 12px; width: 100%;" cellspacing="0" cellpadding="3px;">
        <tr class="km-heading">
            <td colspan="2">*** NON HAZ MAT</td>
            <td colspan="3">OCEAN FREIGHT PAID</td>
            <td colspan="1">WEIGHT(KG)</td>
            <td colspan="1">WEIGHT(LB)</td>
        </tr>
        <tr style="font-size: 15px;">
            <td colspan="2"><b> SEND TELEX RELEASE </b></td>
            <td colspan="3" style="font-size: 12px;"><b> ITN#</b>{{ $export->itn }}</td>
            <td colspan="1">{{ round($vehicleTotalWeightsInKG) }}</td>
            <td colspan="1">{{ round($vehicleTotalWeights) }}</td>
        </tr>
        <tr>
            <td colspan="7">These Comodities, Technology Or Software Were Exported From The United States In The
                Acordance With The Exoirt Administrative Regulations. Diversion Contrary To The U.s. Law Prohibited.
            </td>
        </tr>
    </table>

    <table border="1px" width="100%" style="margin-top: 5px; font-size: 12px; width: 100%;" cellspacing="0">
        <tr>
            <td colspan="4">HEREBY CERTIFY HAVING RECEIVED THE ABOVE DESCRIBED SHIPMENT IN OUTWARDLY GOOD CONDITION FROM
                THE SHIPPER SHOWN IN SECTION "EXPORTER", FOR FORWARDING TO THE ULTIMATE CONSIGNEE SHOWN IN THE SECTION
                "CONSIGNEE" ABOVE. IN WITNESS WHEREOF, THE ____________ NONNEGOTIABLE FCR'S HAVE BEEN SIGNED, AND IF ONE
                (1) IS ACCOMPLISHED BY DELIVERY OF GOODS, ISSUANCE OF A DELIVERY ORDER OR BY SOME OTHER MEANS, THE
                OTHERS SHALL BE AVOIDED IF REQUIRED BY THE FREIGHT FORWARDER, ONE (1) ORIGINAL FCR MUST BE SURRENDERED,
                DULY ENDORSED IN EXCHANGE FOR THE GOODS OR DELIVERY ORDER
            </td>
        </tr>
        <tr>
            <td colspan="1" class="km-heading">AUTHORIZED:</td>
            <td colspan="1"></td>
            <td colspan="1" class="km-heading">DATED AT:</td>
            <td colspan="1"></td>
        </tr>
    </table>
</div>
</body>
</html>
