<style type="text/css">
    td {
        font-family: Arial, Helvetica, sans-serif;
    }

    .km-heading {
        background-color: #D9FBFA;
        font-size: 15px;
        font-weight: bold;
        /*text-align: center;*/
    }

    table {
        font-size: 14px;
    }

    header {
        position: fixed;
        top: -40px;
    }

    footer {
        position: fixed;
        bottom: -30px;
    }

    .km-12s {
        font-size: 12px;
        font-family: Arial, Helvetica, sans-serif;

    }

    .pagenum:before {
        content: counter(page);
    }
</style>

<!DOCTYPE html>
<html>
<head>
    <title>Manifest | {{ env('APP_NAME') }}</title>
</head>
<body>
<header style="width: 100%">
    <table width="100%" style="border-bottom: 1px solid #333;">
        <tr>
            <td>
                <small><strong>Generated By: {{ env('APP_NAME') }}</strong></small>
            </td>
            <td></td>
{{--            <td style="text-align: right;"><small><strong>Generated On: {{ date('r') }}</strong></small></td>--}}
        </tr>
    </table>
</header>

<footer>
    <p style="text-align: center; border-top: 1px solid #333;">Page <span class="pagenum"></span></p>
</footer>

<div>
    <table border="1px" width="100%" cellspacing="0" cellpadding="6">
        <tr>
            <td width="25%">
                <img src="https://backend.aslshippingline.com/images/logo.jpg" width="170px" height="80px" alt="{{ env('APP_NAME') }} logo">
            </td>
            <td width="38%" style="font-weight: bolder;color: black; font-size: 12px; text-align: center;">
                <h5>131 East Gardena<br>Boulevard Gardena, CA 90248<br>Tel: (310) 532-8557</h5>
            </td>
            <td width="37%">
                <table border="1px" width="100%">
                    <tr>
                        <td>MANIFEST</td>
                        <td><span style="font-size: 11px;">{{ $export->ar_number }}</span></td>
                    </tr>
                    <tr>
                        <td>DATE</td>
                        <td>{{ $export->export_date }}</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

    <table border="1px" width="100%" cellspacing="0" cellpadding="1" style="margin-top: 1px;">

        <tr class="km-heading" style="font-weight: bold;">
            <td width="50%">Shipper</td>
            <td width="50%">Notify / Consignee</td>
        </tr>
    </table>

    <table border="1px" width="100%" cellspacing="0" cellpadding="6" style="margin-top: 1px;">

        <tr>
            <td width="50%">
                {{ $export->customer->company_name . ' ' . $export->customer->address_line_1 }} <br>
                {{ data_get($export, 'exporter.state.name') }} <br>
                {{ data_get($export, 'exporter.city.name'). ' '. data_get($export, 'exporter.zip_code') }} <br>
                {{ data_get($export, 'exporter.phone') }}
            </td>
            <td width="50%">
                {{ data_get($export, 'houstan_custom_cover_letter.notify_party_item.consignee_name') }} <br>
                {{ data_get($export, 'houstan_custom_cover_letter.notify_party_item.consignee_address_1') }} <br>
                @if(data_get($export, 'houstan_custom_cover_letter.notify_party_item.phone'))
                    PHONE :{{ data_get($export, 'houstan_custom_cover_letter.notify_party_item.phone') }}
                @endif
            </td>
        </tr>
    </table>

    <table border="1px" width="100%" cellspacing="0" cellpadding="1" style="margin-top: 1px;">
        <tr class="km-heading">
            <td width="100%" align="center" style="font-weight: bold;">Description</td>
        </tr>
    </table>

    @php
        $vehicleTotalWeights = 0;
        foreach($export->vehicles as $vehicle) {
            $vehicleTotalWeights += (int) $vehicle->weight;
        }
        $manifestDate = date('Y-m-d', strtotime($export->created_at));
     @endphp


    <table border="1px" width="100%" cellspacing="1" cellpadding="0" style="margin-top: 1px; border-top: none; border-right: none; border-bottom: none; border-left: none;">
        <tr>
            <td width="20%" class="km-heading"> Vessel/Voyage:</td>
            <td width="25%"> {{ $export->vessel . ' / ' . $export->voyage }}</td>
            <td style="border:none;" width="15%"></td>
            <td style="border:none;" width="15%"></td>
            <td style="border:none; text-align: center;" width="25%"> Weight</td>
        </tr>
        <tr>
            <td width="20%" class="km-heading">Cut Off:</td>
            <td width="25%">{{ $export->cutt_off }}</td>
            <td style="border:none;" width="15%"></td>
            <td style="border:none;" width="15%"></td>

            <td style="border:none;" width="25%">
                <table cellspacing="0" border="1px" width="100%" style="text-align: center;">
                    <tr>
                        <td>{{ $vehicleTotalWeights }}</td>
                    </tr>
                    <tr>
                        <td class="km-heading"> Pieces</td>
                    </tr>
                    <tr>
                        <td> {{ $export->vehicles->count() }}</td>
                    </tr>

                </table>
            </td>
        </tr>
        <tr>
            <td width="20%" class="km-heading">Booking#:</td>
            <td width="25%">{{ $export->booking_number }}</td>
            <td style="border:none;" width="15%"></td>
            <td style="border:none;" width="15%"></td>

            <td style="border:none;" width="25%"></td>
        </tr>
        <tr>
            <td width="20%" class="km-heading">File Ref#:</td>
            <td width="25%">{{ $export->ar_number }}</td>
            <td style="border:none;" width="15%"></td>
            <td style="border:none;" width="15%"></td>

            <td style="border:none;" width="25%"></td>
        </tr>
        <tr>
            <td width="20%" class="km-heading">Container#:</td>
            <td width="25%">{{ $export->container_number }}</td>
            <td style="border:none;" width="15%"></td>
            <td style="border:none;" width="15%"></td>

            <td style="border:none;" width="25%"></td>
        </tr>
        <tr>
            <td width="20%" class="km-heading">Seal#:</td>
            <td width="25%">{{ $export->seal_number }}</td>
            <td style="border:none;" width="15%"></td>
            <td style="border:none;" width="15%"></td>

            <td style="border:none;" width="25%"></td>
        </tr>
        <tr>
            <td width="20%" class="km-heading">Export Terminal:</td>
            <td width="25%">{{ $export->terminal }}</td>
            <td width="20%" class="km-heading" style="text-align: center;">Export Date<br> {{ $export->export_date }}
            <td style="border: none;" width="25%"></td>
            <td width="20%" class="km-heading" style="text-align: center;">Manifest Date<br>{{ $manifestDate }}
        </tr>
    </table>
    <table width="100%" style="font-size: 10px;" border="1px" cellspacing="0" cellpadding="1">
        <tr class="km-heading">
            <td>Year</td>
            <td>Make</td>
            <td>Model</td>
            <td>VIN</td>
            <td>Hat#</td>
            <td>Towing</td>
            <td>Auction Storage</td>
            <td>Title Fee</td>
            <td>Storage Days</td>
            <td>Arrival Date</td>
            <td>Add.Ch.</td>
            <td>Yard Storage</td>
            <td>Keys</td>
        </tr>
        @php
            $totalTowedAmount = 0;
            $totalStorage = 0;
            $totalCharges = 0;
            $totalTitleFees = 0;
        @endphp
        @foreach($export->vehicles as $vehicle)
        @php
            $totalTowedAmount += $vehicle->towed_amount;
            $totalStorage += (int) $vehicle->storage_amount;
            $totalCharges += $vehicle->additional_charges;
            $totalTitleFees += (float) $vehicle->title_amount;

            $towingRequest = $vehicle->towing_request;
            $deliverDate = $towingRequest->deliver_date;
            $storageDays = $deliverDate ? round( ( strtotime($manifestDate) - strtotime( $deliverDate ) ) / ( 60 * 60 * 24 ) ) : 0;
            $storageDays = $storageDays > 30 ? $storageDays - 30 : 0;
        @endphp
        <tr>
            <td>{{ $vehicle->year }}</td>
            <td>{{ $vehicle->make }}</td>
            <td>{{ $vehicle->model }}</td>
            <td>{{ $vehicle->vin }}</td>
            <td>{{ $vehicle->hat_number }}</td>
            <td>{{ $vehicle->towed_amount }}</td>
            <td>0</td>
            <td>{{ $vehicle->title_amount }}</td>
            <td>{{ $storageDays }}</td>
            <td>{{ $towingRequest->deliver_date }}</td>
            <td>{{ $vehicle->additional_charges }}</td>
            <td>{{ $storageDays * 5 }}</td>
            <td>{{ $vehicle->keys ? 'Yes' : 'No' }}</td>
        </tr>
        @endforeach
        <tr>
            <td style="border:1px solid gray; text-align: right;" colspan="5" class="km-heading">Total:</td>
            <td style="text-align: center;">{{ $totalTowedAmount }}</td>
            <td style="text-align: center;">0</td>
            <td style="text-align: center;">{{ $totalStorage }}</td>
            <td></td>
            <td></td>
            <td style="text-align: center;">{{ $totalCharges }}</td>
            <td style="text-align: center;">{{ $totalTitleFees }}</td>
            <td></td>
        </tr>
    </table>

    <table width="100%">
        <tr>
            <td colspan="10">VEHICLES ARE BRACED AND BLOCKED.FUEL TANKS HAVE BEEN SECURELY CLOSED.THE KEYS ARE NOT IN
                THE IGNITION.BATERIES ARE SECURED AND FASTENED IN THE UPRIGHT POSITION AND PROTECTED
                AGAINST SHORT CIRCUITS. THE FUEL TANKS ARE EMPTY AND THE ENGINE STOPPED DUE TO LACK OF
                FUEL.THE VEHICLES HAVE BEEN LOADED INTO THE CONTAINER IN RANCHO DOMINGUEZ, CALIFORNIA
            </td>
        </tr>
    </table>
    <table border="1px" cellspacing="0" width="100%" style="margin-top: 1px;">
        <tr>
            <td width="20%" class="km-heading">Received in Good Order</td>
            <td width="30%"></td>
            <td width="20%" class="km-heading">Date/Time</td>
            <td width="30%"></td>

        </tr>
    </table>
    <table border="1px" cellspacing="0" width="100%" style="margin-top: 1px;">
        <tr>
            <td width="20%" class="km-heading">Drivers Signature</td>
            <td width="30%"></td>
            <td width="20%" class="km-heading">Date/Time</td>
            <td width="30%"></td>
        </tr>
    </table>
    <table border="1px" cellspacing="0" width="100%" style="margin-top: 1px;">
        <tr>
            <td width="20%" class="km-heading">Shippers Signature</td>
            <td width="30%"></td>
            <td width="20%" class="km-heading">Date/Time</td>
            <td width="30%"></td>
        </tr>
    </table>
    <table>
        <tr>
            <td colspan="4" style="font-size: 11px;">The liability of {{ env('APP_NAME') }}, for any reason shall in no case
                exceed $0.50 cent per hundred pounds or $500.00 per
                shipment whichever is less. {{ env('APP_NAME') }} will not be liable for consequential or incidental damages or
                loss of profits.
                Net 15 days, with a monthly finance charge of 1.5% on all balances over thirty days. {{ env('APP_NAME') }}
                reserves the right
                to hold or lien cargo for nonpayment Payment is required within (15) days of presentation. Failure to
                pay billed
                charges may result in lien on future shipment, including cost of storage and appropriate security for
                the subsequent
                shipment(s) held pursuant to California Civil Code, Section 3051.5 {{ env('APP_NAME') }} is a freight forwarding
                company,
                and we are not liable for any charges if your container is stopped by the US Customs for random, routine
                procedural
                checks. On our end, we will always make sure to have all the necessary paperwork attached when we ship
                your
                container and take the correct steps to meet all requirements. However, due to US Customs policy, they
                can always
                stop a container for random inspections. Although we will try our best to help you with anything we can,
                we are not
                responsible for this stop or any fees related to it because they are a completely separate entity from
                us. You will be
                liable to US Customs and all charges pertaining to this stop will be covered by you and paid directly to
                them.
            </td>
        </tr>
    </table>


</div>
</body>
</html>
