<?php

return [
    'table_mapping' => [
        /*
        'location'                    => [ 'table' => 'locations', 'unique_column' => 'id' ],*/
//        'old_db_table' => 'new_db_table',
        'user'                        => [ 'table' => 'users', 'unique_column' => 'id' ],
        'customer'                    => [ 'table' => 'customers', 'unique_column' => 'user_id' ],
        'vehicle'                     => [ 'table' => 'vehicles', 'unique_column' => 'id' ],
        'documents'                   => [ 'table' => 'vehicle_documents', 'unique_column' => 'id' ],
        'vehicle_export'              => [ 'table' => 'vehicle_exports', 'unique_column' => 'id' ],
        'towing_request'              => [ 'table' => 'towing_requests', 'unique_column' => 'id' ],
        'vehicle_features'            => [ 'table' => 'vehicle_features', 'unique_column' => 'id' ],
        'vehicle_condition'           => [ 'table' => 'vehicle_conditions', 'unique_column' => 'id' ],
        'images'                      => [ 'table' => 'vehicle_images', 'unique_column' => 'id' ],
        'export'                      => [ 'table' => 'exports', 'unique_column' => 'id' ],
        'export_images'               => [ 'table' => 'export_images', 'unique_column' => 'id' ],
        'dock_receipt'                => [ 'table' => 'dock_receipts', 'unique_column' => 'export_id' ],
        'houstan_custom_cover_letter' => [ 'table' => 'houstan_custom_cover_letters', 'unique_column' => 'export_id' ],
        'customer_documents'          => [ 'table' => 'customer_documents', 'unique_column' => 'id' ],
        'pricing'                     => [ 'table' => 'pricings', 'unique_column' => 'id' ],
        'invoice'                     => [ 'table' => 'invoices', 'unique_column' => 'id' ],
        'condition'                   => [ 'table' => 'conditions', 'unique_column' => 'id' ],
        'consignee'                   => [ 'table' => 'consignees', 'unique_column' => 'id' ],
        'features'                    => [ 'table' => 'features', 'unique_column' => 'id' ],
        'notification'                => [ 'table' => 'notifications', 'unique_column' => 'id' ],
        'vehicle_weight'              => [ 'table' => 'vehicle_weights', 'unique_column' => 'id' ],
        'note'                        => [ 'table' => 'notes', 'unique_column' => 'id' ],
        'vehicle_claim'               => [ 'table' => 'vehicle_claims', 'unique_column' => 'id' ],
    ],
    'field_mapping' => [
        'users'                        => [
            'id'         => 'id',
            'username'   => 'username',
            'email'      => 'email',
            'password'   => 'password_hash',
            'auth_key'   => 'auth_key',
            'created_by' => 'created_by',
            'updated_by' => 'updated_by',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
        ],
        'locations'                    => [
            'id'   => 'id',
            'name' => 'location_name',
        ],
        'customers'                    => [
            'user_id'            => 'user_id',
            'customer_name'      => 'customer_name',
            'company_name'       => 'company_name',
            'phone'              => 'phone',
            'address_line_1'     => 'address_line_1',
            'address_line_2'     => 'address_line_2',
            'zip_code'           => 'zip_code',
            'tax_id'             => 'tax_id',
            'created_by'         => 'created_by',
            'updated_by'         => 'updated_by',
            'legacy_customer_id' => 'legacy_customer_id',
            'fax'                => 'fax',
            'trn'                => 'trn',
            'phone_two'          => 'phone_two',
            'other_emails'       => 'other_emails',
            'note'               => 'note',
            'loading_type'       => 'loading_type',
            'created_at'         => 'created_at',
            'updated_at'         => 'updated_at',
        ],
        'exports'                      => [
            'id'                  => 'id',
            'export_date'         => 'export_date',
            'loading_date'        => 'loading_date',
            'broker_name'         => 'broker_name',
            'booking_number'      => 'booking_number',
            'eta'                 => 'eta',
            'ar_number'           => 'ar_number',
            'xtn_number'          => 'xtn_number',
            'seal_number'         => 'seal_number',
            'container_number'    => 'container_number',
            'cutt_off'            => 'cutt_off',
            'vessel'              => 'vessel',
            'voyage'              => 'voyage',
            'terminal'            => 'terminal',
            'streamship_line'     => 'streamship_line',
            'destination'         => 'destination',
            'itn'                 => 'itn',
            'contact_details'     => 'contact_details',
            'special_instruction' => 'special_instruction',
            'container_type'      => 'container_type',
            'port_of_loading'     => 'port_of_loading',
            'port_of_discharge'   => 'port_of_discharge',
            'export_invoice'      => 'export_invoice',
            'bol_note'            => 'bol_note',
            'customer_user_id'    => 'customer_user_id',
            'bol_remarks'         => 'bol_remarks',
            'note'                => 'note2',
            'created_by'          => 'created_by',
            'updated_by'          => 'updated_by',
            'created_at'          => 'created_at',
            'updated_at'          => 'updated_at',
        ],
        'vehicles'                     => [
            'id'                 => 'id',
            'hat_number'         => 'hat_number',
            'vehicle_type'       => 'vehicle_type',
            'year'               => 'year',
            'color'              => 'color',
            'model'              => 'model',
            'make'               => 'make',
            'vin'                => 'vin',
            'weight'             => 'weight',
            'pieces'             => 'pieces',
            'value'              => 'value',
            'license_number'     => 'license_number',
            'towed_from'         => 'towed_from',
            'lot_number'         => 'lot_number',
            'towed_amount'       => 'towed_amount',
            'storage_amount'     => 'storage_amount',
            'status'             => 'status',
            'load_status'        => 'load_status',
            'check_number'       => 'check_number',
            'additional_charges' => 'additional_charges',
            'location_id'        => 'location',
            'customer_user_id'   => 'customer_user_id',
            'towing_request_id'  => 'towing_request_id',
            'is_export'          => 'is_export',
            'title_amount'       => 'title_amount',
            'container_number'   => 'container_number',
            'keys'               => 'keys',
            'key_note'           => 'key_note',
            'notes_status'       => 'notes_status',
            'prepared_by'        => 'preparedby',
            'auction_at'         => 'auction_at',
            'vcr'                => 'vcr',
            'note'               => 'note2',
            'created_by'         => 'created_by',
            'updated_by'         => 'updated_by',
            'created_at'         => 'created_at',
            'updated_at'         => 'updated_at',

        ],
        'vehicle_exports'              => [
            'id'               => 'id',
            'vehicle_id'       => 'vehicle_id',
            'export_id'        => 'export_id',
            'customer_user_id' => 'customer_user_id',
        ],
        'towing_requests'              => [
            'id'                  => 'id',
            'condition'           => 'condition',
            'damaged'             => 'damaged',
            'pictures'            => 'pictures',
            'towed'               => 'towed',
            'title_received'      => 'title_recieved',
            'title_received_date' => 'title_recieved_date',
            'title_number'        => 'title_number',
            'title_state'         => 'title_state',
            'towing_request_date' => 'towing_request_date',
            'pickup_date'         => 'pickup_date',
            'deliver_date'        => 'deliver_date',
            'note'                => 'note',
            'title_type'          => 'title_type',
        ],
        'export_images'                => [
            'id'        => 'id',
            'export_id' => 'export_id',
            'name'      => 'name',
            'thumbnail' => 'thumbnail',
            'baseurl'   => 'baseurl',
            'type'      => 'type',
        ],
        'vehicle_images'               => [
            'id'         => 'id',
            'name'       => 'name',
            'thumbnail'  => 'thumbnail',
            'vehicle_id' => 'vehicle_id',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
            'created_by' => 'created_by',
            'updated_by' => 'updated_by',
            'baseurl'    => 'baseurl',
        ],
        'conditions'                   => [
            'id'   => 'id',
            'name' => 'name',
        ],
        'vehicle_conditions'           => [
            'id'           => 'id',
            'vehicle_id'   => 'vehicle_id',
            'condition_id' => 'condition_id',
            'value'        => 'value',
        ],
        'consignees'                   => [
            'id'                  => 'id',
            'customer_user_id'    => 'customer_user_id',
            'consignee_name'      => 'consignee_name',
            'consignee_address_1' => 'consignee_address_1',
            'consignee_address_2' => 'consignee_address_2',
//            'city'                => 'city',
//            'state'               => 'state',
//            'country'             => 'country',
            'zip_code'            => 'zip_code',
            'phone'               => 'phone',
            'created_by'          => 'created_by',
            'updated_by'          => 'updated_by',
            'created_at'          => 'created_at',
            'updated_at'          => 'updated_at',
        ],
        'customer_documents'           => [
            'id'               => 'id',
            'file'             => 'file',
            'customer_user_id' => 'customer_user_id',
        ],
        'vehicle_documents'            => [
            'id'         => 'id',
            'name'       => 'name',
            'vehicle_id' => 'vehicle_id',
            'invoice_id' => 'invoice_id',
            'created_by' => 'created_by',
            'updated_by' => 'updated_by',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
        ],
        'features'                     => [
            'id'   => 'id',
            'name' => 'name',
        ],
        'vehicle_features'             => [
            'id'          => 'id',
            'vehicle_id'  => 'vehicle_id',
            'features_id' => 'features_id',
            'value'       => 'value',
        ],
        'notifications'                => [
            'id'          => 'id',
            'subject'     => 'subject',
            'message'     => 'message',
            'is_read'     => 'is_read',
            'status'      => 'status',
            'user_id'     => 'user_id',
            'expire_date' => 'expire_date',
            'only_notify' => 'only_notify',
            'created_by'  => 'created_by',
            'updated_by'  => 'updated_by',
            'created_at'  => 'created_at',
            'updated_at'  => 'updated_at',
        ],
        'pricings'                     => [
            'id'           => 'id',
            'upload_file'  => 'upload_file',
            'month'        => 'month',
            'str_month'    => 'str_month',
            'pricing_type' => 'pricing_type',
            'status'       => 'status',
            'description'  => 'description',
            'created_by'   => 'created_by',
            'updated_by'   => 'updated_by',
            'created_at'   => 'created_at',
            'updated_at'   => 'updated_at',

        ],
        'vehicle_weights'              => [
            'id'     => 'id',
            'year'   => 'year',
            'maker'  => 'maker',
            'model'  => 'model',
            'weight' => 'weight',
        ],
        'notes'                        => [
            'id'          => 'id',
            'description' => 'description',
            'export_id'   => 'export_id',
            'vehicle_id'  => 'vehicle_id',
            'image_url'   => 'imageurl',
            'admin_view'  => 'admin_view',
            'cust_view'   => 'cust_view',
            'created_by'  => 'created_by',
            'updated_by'  => 'updated_by',
            'created_at'  => 'created_at',
            'updated_at'  => 'updated_at',
        ],
        'houstan_custom_cover_letters' => [
            'export_id'              => 'export_id',
            'vehicle_location'       => 'vehicle_location',
            'exporter_id'            => 'exporter_id',
            'exporter_type_issuer'   => 'exporter_type_issuer',
            'transportation_value'   => 'transportation_value',
            'exporter_dob'           => 'exporter_dob',
            'ultimate_consignee_dob' => 'ultimate_consignee_dob',
            'consignee'              => 'consignee',
            'notify_party'           => 'notify_party',
            'menifest_consignee'     => 'menifest_consignee',
        ],
        'invoices'       => [
            'id'                  => 'id',
            'export_id'           => 'export_id',
            'customer_user_id'    => 'customer_user_id',
            'consignee_id'        => 'consignee_id',
            'total_amount'        => 'total_amount',
            'paid_amount'         => 'paid_amount',
            'export_invoice'      => 'export_invoice',
            'note'                => 'note',
            'adjustment_damaged'  => 'adjustment_damaged',
            'adjustment_storage'  => 'adjustment_storage',
            'adjustment_discount' => 'adjustment_discount',
            'adjustment_other'    => 'adjustment_other',
            'currency'            => 'currency',
            'discount'            => 'discount',
            'before_discount'     => 'before_discount',
            'upload_invoice'      => 'upload_invoice',
            'seen_by_customer'    => 'seen_by_customer',
            'clearance_invoice'   => 'clearance_invoice',
            'note2'               => 'note2',
            'created_by'          => 'created_by',
            'updated_by'          => 'updated_by',
            'created_at'          => 'created_at',
            'updated_at'          => 'updated_at',
        ],
        'vehicle_claims' => [
            'id'               => 'id',
            'vehicle_id'       => 'vehicle_id',
            'export_id'        => 'export_id',
            'customer_user_id' => 'customer_user_id',
            'approved_by'      => 'approved_by',
            'remarks'          => 'remarks',
            'claim_amount'     => 'claim_amount',
            'approved_amount'  => 'approved_amount',
            'approved_date'    => 'approved_date',
            'create_date'      => 'create_date',
            'claim_status'     => 'claim_status',
            'admin_remarks'    => 'admin_remarks',
            'vehicle_part'     => 'vehicle_part',
            'other_parts'      => 'other_parts',
            'cust_view'        => 'cust_view',
            'admin_view'       => 'admin_view',
            'lot_number'       => 'lot_number',
        ],
        'dock_receipts'  => [
            'export_id'                       => 'export_id',
            'awb_number'                      => 'awb_number',
            'export_reference'                => 'export_reference',
            'forwarding_agent'                => 'forwarding_agent',
            'domestic_routing_instructions'   => 'domestic_routing_insctructions',
            'pre_carriage_by'                 => 'pre_carriage_by',
            'place_of_receipt_by_pre_carrier' => 'place_of_receipt_by_pre_carrier',
            'exporting_carrier'               => 'exporting_carrier',
            'final_destination'               => 'final_destination',
            'loading_terminal'                => 'loading_terminal',
            'container_type'                  => 'container_type',
            'number_of_packages'              => 'number_of_packages',
            'by'                              => 'by',
            'date'                            => 'date',
            'auto_receiving_date'             => 'auto_recieving_date',
            'auto_cut_off'                    => 'auto_cut_off',
            'vessel_cut_off'                  => 'vessel_cut_off',
            'sale_date'                       => 'sale_date',
        ],
    ],
];
